- browser-app/package.json
- electron-app/package.json
- yarn.lock
Removes the `@theia/typescript` extension from the examples
which leads to a multi-injector error from inversify.
Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>
> dependencies: remove deprecated extensions

- viewer-prototype/src/browser/trace-viewer/components/xy-output-component.tsx
> xy-output-component: check line chart reference before accessing it

- viewer-prototype/package.json
- viewer-prototype/src/browser/style/trace-explorer.css
- viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
- viewer-prototype/src/browser/trace-viewer/components/abstract-tree-output-component.tsx
- viewer-prototype/src/browser/trace-viewer/components/trace-context-component.tsx
- viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
- viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
- viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
- viewer-prototype/src/common/experiment-manager.ts
- yarn.lock
- Added support of opening single and multiple traces in an experiment
- Upload each trace and create experiment using ExperimentManager
- Implemented simple trace detection algorithm. If the selection is a
directory, then the files system is recursively searched for CTF traces
by finding the metadata file. Otherwise a single file is opened as trace
- The detection of traces is done in the front-end. This needs to be
replaced by a backend service that avoids querying the file system
directly from the frontend.
- Updated class, method and variable names to reflect support of
experiments
- Update Trace Explorer to show available experiments and it's traces.
This visualized list is very basic and needs to be improved.
> Add support of experiments consisting of 1 or more traces

- viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
- viewer-prototype/src/common/experiment-manager.ts
- viewer-prototype/src/common/trace-manager.ts
When opening a trace with the same name as another experiment, the experiment
that contains it will have a conflict on the server. The client should
retry posting it with a different name until it succeeds or another
error occurs.
The title of the trace viewer should also be updated to represent the
actual name of the experiment.
> Handle conflicting experiments when opening

- README.md
- browser-app/package.json
- electron-app/package.json
- package.json
- viewer-prototype/README.md
- yarn.lock
As per recent discussion, it sounds like it would be useful to add
C/C++ support in the example apps in this repo.
update: I added another commit with some quick improvements:
- added/documented scripts in root `package.json`: `start:browser` and `start:electron`. 
- added skeleton README for the extension (eventually the main doc for the extension's npm page)
- mention of electron version of example app in main README
Signed-off-by: Marc Dumais <marc.dumais@ericsson.com>
> Add C/C++ support to browser and electron example apps

- .gitignore
- .gitpod.dockerfile
- .gitpod.yml
- LICENSE.gitpod.md
- README.md
- browser-app/package.json
- electron-app/electron-builder.yml
- electron-app/package.json
- electron-app/resources/todo.txt
- electron-app/scripts/theia-trace-main.js
- package.json
- viewer-prototype/package.json
- yarn.lock
Added the open-vsx registry integration in the example app. One can browse and install
VS Code extensions from the extensions' view. As well added a set of VS Code Built-ins
to support syntax highlighting and more for multiple languages, like VS Code does OOTB.
Added vscode extensions vscode-clangd and cdt-gdb-vscode (Electron only - the browser
version uses @theia/cpp-debug which does not work well ATM in electron-builder
packagings).
Added an electron-builder config for Linux, which generates an .Appimage and a Debian
package.
Signed-off-by: Marc Dumais <marc.dumais@ericsson.com>
> Update example apps to support open-vsx, support C/C++ with vscode extensions

- viewer-prototype/src/browser/trace-explorer/trace-explorer-contribution.ts
- viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
Fixes: #80
The following commit adds the `Trace Explorer` to the **default layout** of the application.
Adding the view to the default layout will make it more discoverable and accessible to end-users, and can later be automatically opened if a trace is identified.
1. checkout the branch, build the application and start: `yarn && (cd browser-app && yarn start)`
2. execute the command `Reset Workbench Layout`\
(using the command palette <kbd>ctrlcmd</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>)\
(the command resets the layout to it's default (without local-storage storing the previous layout))
3. when the application is reloaded, the view should be present in the sidebar.
<div align='center'>
</div>
- as a reviewer, I agree to behave in accordance with [the review …
> trace-explorer: add to default layout

- .github/workflows/build.yml
- package.json
**What it does**
Closes #78 
The following pull-request adds .yml config file for Github Actions CI. The workflow includes running tests on ubuntu, macos, windows with node version 10.x
Code linting is run only on ubuntu with autofix and supports for `eslint` and `prettier` using [samuelmeuli/lint-action@v1](https://github.com/samuelmeuli/lint-action)
The change is part of the: [issues/78: Add a CI for the trace extension](https://github.com/theia-ide/theia-trace-extension/issues/78)
Signed-off-by: Quoc-Hao TRAN \<quoc-hao.tran@polymtl.ca\>
> Github Actions CI test & lint

- .gitpod.dockerfile
- .gitpod.yml
- browser-app/package.json
- electron-app/package.json
Fixes #106
A few little tweaks are necessary to accommodate the new Electron and node versions.   ATM the Electron example app fails at runtime when running on Gitpod, because of a missing a dynamic library:
`/workspace/theia-trace-extension/node_modules/electron/dist/electron: error while loading shared libraries: libgbm.so.1: cannot`
We need to update the `Gitpod` config so the dockerfile used for this repoi will contain a new Ubuntu package, required for Electron 9. This config file originally came from the main Theia repo, and the updated version is the same. See LICENSE.gitpod.md for more details.
Here's where the `--no-sandbox` idea came from - it permits the Electron version of the example app to start in Gitpod:
https://github.com/eclipse-theia/theia/pull/7968#issuecomment-65902974 …
> update repo for Electron 9 / node 12

- viewer-prototype/src/browser/trace-viewer/components/table-output-component.tsx
Uses ag-grid 'infinite' row model type
Added option to display event index. (very useful in testing)
Tested on Chrome Version 85.0.4183.83 (Official Build) (64-bit) using samples traces in TraceCompassTutorialTraces
Signed-off-by: Akshay Sharma <akshay.c.sharma@ericsson.com>
> Events table infinite scroll.

- .github/workflows/build.yml
- browser-app/package.json
- electron-app/package.json
- yarn.lock
**Description**
The pull-request includes the following changes:
(ideally the `engines` field should be at the root `package.json` and not defined for each example app)
---
cc @bhufmann the following changes should help resolve the issues you were experiencing regarding building the repo and including newer versions of `@theia`.
> repo: misc cleanup

- viewer-prototype/src/browser/trace-viewer/components/abstract-output-component.tsx
- viewer-prototype/src/browser/trace-viewer/components/abstract-tree-output-component.tsx
- viewer-prototype/src/browser/trace-viewer/components/table-output-component.tsx
- viewer-prototype/src/browser/trace-viewer/components/timegraph-output-component.tsx
- viewer-prototype/src/browser/trace-viewer/components/trace-context-component.tsx
- viewer-prototype/src/browser/trace-viewer/components/utils/output-component-style.ts
- viewer-prototype/src/browser/trace-viewer/components/utils/timegraph-container-component.tsx
- viewer-prototype/src/browser/trace-viewer/components/xy-output-component.tsx
- yarn.lock
Commit related technical details:
1. WidthProvider has a bug. (https://github.com/STRML/react-grid-layout/issues/961). Had to work around it.
2. Syntax to use ReactGridLayout with Custom Components, while passing resized dimensions to children. https://github.com/STRML/react-grid-layout/issues/299#issuecomment-524959229
> Allow height resizing of tables and charts.

- viewer-prototype/src/browser/trace-viewer/components/trace-context-component.tsx
Change the time format to T.SSS SSS SSS where T is in seconds. Make sure
each group of digits SSS is zero-padded.
> Change numberTranslator format

- viewer-prototype/src/browser/trace-viewer/components/null-output-component.tsx
- viewer-prototype/src/browser/trace-viewer/components/trace-context-component.tsx
For example, provider type DATA_TREE is currently not implemented and
when selecting such provider (e.g. Function Duration Statistics) the
trace container crashes and the trace has to be closed first before
being able to continue.
This patch shows avoids the crash and shows a warning message instead.
> #144: Show 'Not implemented yet!' for unsupported data provider type

- viewer-prototype/src/browser/trace-viewer/components/abstract-tree-output-component.tsx
- viewer-prototype/src/browser/trace-viewer/components/data-providers/style-provider.ts
- viewer-prototype/src/browser/trace-viewer/components/data-providers/tsp-data-provider.ts
- viewer-prototype/src/browser/trace-viewer/components/table-output-component.tsx
- viewer-prototype/src/browser/trace-viewer/components/timegraph-output-component.tsx
- viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/column-header.tsx
- viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/entry-tree.tsx
- viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/sort.tsx
- viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/table-body.tsx
- viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/table-cell.tsx
- viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/table-header.tsx
- viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/table-row.tsx
- viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/table.tsx
- viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/tree-node.tsx
- viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/tree.tsx
- viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/utils.tsx
- viewer-prototype/src/browser/trace-viewer/components/xy-output-component.tsx
- viewer-prototype/src/common/utils/value-hash.ts
- yarn.lock
The trace server protocol and the tsp-typescript-client have been
updated. This makes the trace extension match the newer versions.
It updates the filter-tree (left part of xy and timegraphs) to use
labels and column headers instead of extra keys.
Signed-off-by: Geneviève Bastien <gbastien@versatic.net>
> Align code with the TSP specification

- viewer-prototype/package.json
- yarn.lock
The version of react-grid-layout used by the application used the
renamed componentWillReceiveProps method and resulted in a warning when
running the extension. The warning suggests upgrading the package.
Signed-off-by: Geneviève Bastien <gbastien@versatic.net>
> Upgrade react-grid-layout to ^1.1.0

- viewer-prototype/src/browser/trace-viewer/components/table-output-component.tsx
By setting the enableColResize property to true on the ag-grid,
users can resize any columns in the events table.
> Add support for column resizing

- packages/base/src/experiment-manager.ts
- packages/base/src/trace-manager.ts
- viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
- viewer-prototype/src/browser/tsp-client-provider.ts
Wait for experiment deletion response to be received before attempting
to close its traces.
Handle trace and experiment deletion response and do not remove it from
its manager if the deletion was rejected by the trace server.
> Close traces after experiment and handle deletion rejection

- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/style/trace-context-style.css
This PR fixes the positioning of the placeholder text when opening a trace. Previously the text was off-centered and non-responsive such that the text would be cut-off in certain viewport widths.
This PR also updates the text based on @ssmagula's recommendations. I understand there is a desire to obviate this step in future iterations, but this should improve things in the meantime!
| Before | After |
| ------ | ------ |
|![image](https://user-images.githubusercontent.com/14880569/103942654-5731f200-50f6-11eb-9a39-ccf4890c54fa.png)|![image](https://user-images.githubusercontent.com/14880569/103942578-3d90aa80-50f6-11eb-9340-2d984476a45c.png)|
> Fixed placeholder text positioning and updated placeholder text

- browser-app/package.json
- electron-app/package.json
- viewer-prototype/package.json
- viewer-prototype/src/browser/trace-server-bindings.ts
- viewer-prototype/src/browser/trace-server-preference.ts
- viewer-prototype/src/browser/trace-server-status.ts
- viewer-prototype/src/browser/trace-server-url-provider-frontend-impl.ts
- viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
- viewer-prototype/src/common/trace-server-config.ts
- viewer-prototype/src/common/trace-server-url-provider.ts
- viewer-prototype/src/common/trace-viewer-environment.ts
- viewer-prototype/src/node/index.ts
- viewer-prototype/src/node/trace-server-backend-module.ts
- viewer-prototype/src/node/trace-server-service.ts
- viewer-prototype/tsconfig.json
Set the default values for the trace server preferences
Read the trace server preference values and spawn the server from the path specified in the
preferences
fixes #191
fixes #184
Signed-off-by: Ankush Tyagi ankush.tyagi@ericsson.com
> Add preference settings for trace configuration

- packages/react-components/src/components/timegraph-output-component.tsx
To provide annotation markers the output styles needed to defined
in the list of style provided through the fetch style method which
are referenced by the parent style key in the annotation itself.
This patch makes it possible to supply the OutputElementStyle inside
the annotation without using the parent style key.
> Support inband OutputElementStyle for annotations

- packages/base/src/signal-manager.ts
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
depends on https://github.com/theia-ide/timeline-chart/pull/85
> Sync event timestamp with timegraph

- viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
**What it does**
Fixes https://github.com/theia-ide/theia-trace-extension/issues/215
The following commit updates the `trace-explorer-widget` so that it is closable (using the `title.closable` option (which is ultimately used by the `close` command in the shell tabbar.
- [Reference](https://github.com/eclipse-theia/theia/blob/db4b2e7159aa68f09577dfc212909d97f3e2d1af/packages/core/src/browser/common-frontend-contribution.ts#L648-L656).
**How to test**
- build the changes and start the application
- right-click on the `trace explorer` tab and select `close`
- the view should close
Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>
> trace-explorer: update options to make view closable

- packages/base/src/signal-manager.ts
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/style/trace-explorer.css
- viewer-prototype/src/browser/theia-message-manager.ts
- viewer-prototype/src/browser/trace-explorer/output-added-signal-payload.tsx
- viewer-prototype/src/browser/trace-explorer/trace-explorer-contribution.ts
- viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-analysis-widget.tsx
- viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-opened-traces-widget.tsx
- viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-placeholder-widget.tsx
- viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-tooltip-widget.tsx
- viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
- viewer-prototype/src/browser/trace-viewer/trace-viewer-commands.ts
- viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
- viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
- viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
This MR applies several frontend fixes to the Trace Explorer Widget including:
- Wrap each 'sub widget' inside a panel layout to allow for view flexibility, drag/drop, expand/collapse, resize
- Address explorer-widget responsiveness, rows now adjust according to widget width (partially addresses #30)
- Add on-hover behavior to lists, and change to 'pointer' cursor
- Fix focus timeout issue when Trace Viewer widgets are activated, addresses #182 
- Fix double scrollbar from appearing in lists
- Fix some circular dependency issues
- Minor CSS fixes for consistency inside widget with Theia
- Refactoring of injection to use parameter style with postConstructor vs. constructor for extensibility, adjust `.bind` calls to Theia arrow function style
- Fixed duplicate registration of Open Trace …
> Panelize trace explorer + other frontend fixes

- viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
Electron doesn't support opening a file dialog that allows selecting a
single file or a directory. This patch changes the implementation to
allow only the selection of directories. With this change a user can
select a directory that is a single CTF trace or a directory that
contains multiple CTF traces to be opened in the trace viewer after
clicking on the "Open Trace" button in the Trace Explorer as well as the
"Open Trace" command from the command palette (CTRL+SHIFT+P).
Traces that are a single file, cannot be opened from there but can be
opened using the context sensitive menu "Open With -> Trace Viewer"
from the regular file explorer of the application.
fixes #227
> Use directory chooser only for open trace dialog

- viewer-prototype/src/browser/trace-server-status.ts
- viewer-prototype/src/node/trace-server-service.ts
Signed-off-by: Colin Grant <colin.grant@ericsson.com>
This PR adds a temporary status message when the user gestures to start or stop the trace server.
To test:
1. Point your trace viewer executable and port preferences to good locations
2. Click `Start trace server` in the bottom left status bar.
3. See a message that indicates that server is starting.
4. ... wait < 10 seconds
5. See a change indicating that the server has started
6. Kill the server, see the same message
1. Point your preferences to a bad location (e.g. non-existent file, occupied port)
2. Try to start server
3. In <= 10 seconds you should see a failure message, and the display should revert to the previous state.
There is substantial overlap with #226, which supplies more exact error handling.
> Pending Message on Server Start/Stop

- viewer-prototype/package.json
- viewer-prototype/src/browser/trace-server-status.ts
- viewer-prototype/src/common/trace-server-config.ts
- viewer-prototype/src/node/trace-server-service.ts
- yarn.lock
This PR adds error handling for the start/stop trace server. It also prevents the user from accidentally killing a process through the preferences settings. 
Steps to test:
- Provide an incorrect path for the executable and click the start trace server button. 
- Provide a busy port in the preferences settings and click the start trace server button.
You should see a Toast message with a detailed error.
> Support error handling for start/stop trace server

- packages/react-components/src/components/data-providers/style-provider.ts
- packages/react-components/src/components/timegraph-output-component.tsx
Fetch the style model from the style provider when the component is
mounted, not every time the component is updated if the outputStatus is
not COMPLETED.
> Fetch the style model only once

- packages/base/src/experiment-manager.ts
- packages/base/src/signal-manager.ts
- packages/base/src/trace-manager.ts
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-commands.ts
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-contribution.ts
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-opened-traces-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-commands.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
On Click of 'x' in trace-viewer tab doesn't delete the experiment from trace explorer.
Added a context menu to open, close and delete traces.
fixes #149
> Decouple delete experiments from trace-viewer

- theia-extensions/viewer-prototype/src/browser/trace-server-status.ts
- yarn.lock
Closes #70
Instead of requested the experiments to see if the server is alive, use
the more light-weight checkHealth method.
Signed-off-by: Geneviève Bastien <gbastien@versatic.net>
> Use the checkHealth method to check server status

- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-commands.ts
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-contribution.ts
Fixes: #289
The following commit fixes the issue where a duplicate `open trace` command was present in the command palette. Instead of registering the command with a label (which makes it show up in the command palette), the label is added to the menu only.
_Note_: only commands with `labels` will show up in the command palette.
Signed-off-by: vince-fugnitto <vincent.fugnitto@ericsson.com>
> menu: fix duplicate 'open trace' command

- packages/react-components/src/components/timegraph-output-component.tsx
Useful to align markers vertically.
Signed-off-by: Matthew Khouzam <matthew.khouzam@ericsson.com>
> Propagate vertical alignment style.

- packages/react-components/style/output-components-style.css
fixes #216
-The ag-grid has default color for selected row which isn't consistent
with theia's font family and font size. This change will override those
default values.
> Fixed event_table component's font-family/font-size

- packages/react-components/package.json
- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/tooltip-component.tsx
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/tsconfig.json
- yarn.lock
> Add tooltip support for timegraph states

- packages/react-components/src/components/trace-context-component.tsx
The name of the trace explorer has been change to viewer, update
the warning message to reflect this.
Signed-off-by: Matthew Khouzam <matthew.khouzam@ericsson.com>
> Change "no view" warning to direct users to trace viewer tab

- packages/react-components/src/components/data-providers/tsp-data-provider.ts
- packages/react-components/src/components/timegraph-output-component.tsx
- yarn.lock
This change makes use of the getData provider of the time-graph-chart.
Another way of implementing it would to change time-graph-chart-arrows  to have its own data provider.
This change fixes #39 and it is dependent on:
- github.com/theia-ide/timeline-chart/pull/115
- github.com/theia-ide/tsp-typescript-client/pull/19
- git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/177071
> Add support for arrows

- packages/react-components/src/components/data-providers/style-properties.ts
- packages/react-components/src/components/data-providers/style-provider.ts
- packages/react-components/src/components/timegraph-output-component.tsx
The OutputElementStyle's values map properties can now override the
properties defined for the style identified by the parent key.
A multi-level hierarchy of parent styles is supported. Style composition
by using a comma-delimited list of parent keys is supported.
The 'background-color', 'height', 'border-style', 'border-color' and
'border-width' properties are supported for time graph states.
The 'symbol-type', 'color', 'height' and 'vertical-align' properties are
supported for time graph annotations.
The 'opacity' property and '-blend' modifier are supported for color
styles.
The '-factor' modifier is supported for number styles.
> Support style hierarchy and composition in StyleProvider

- packages/react-components/src/trace-explorer/trace-explorer-opened-traces-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-opened-traces-widget.tsx
Related to #317 
I changed the names of the variables example doubleClick to click 
I removed the handleOnExperimentSelected variable from the onClick event because I don't see its use in this event, this variable was not called. 
here is the result.
> Single-click to select or open trace

- packages/react-components/src/components/table-output-component.tsx
> Populate properties window on click of a row in events table

- packages/react-components/src/components/data-providers/tsp-data-provider.ts
- packages/react-components/src/components/timegraph-output-component.tsx
- yarn.lock
Move the fetch tooltip implementation to the TspDataProvider class.
Provide a method to fetch state tooltip and a method to fetch annotation
tooltip. Create the requested element for the request from the element
model.
Add the category to the annotation model when fetching annotations.
Adapt the tooltip content according to the type of element.
> Support tooltip for annotations

- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
I have filtered out the view type that is not implemented in the client side (DATA_TREE). The expected result is that views of this type are not displayed in the available views 
Contributes towards fixing #296
**Before**
**After**
In these two images, we notice that the Futex contention analysis is not shown in the next image because this view has a DATA_TREE type. 
> Hide analysis that is not implemented on the client side

- packages/react-components/style/output-components-style.css
We can now click and drag to move across the entire title bar 
Fixes #239
**Here is the result**
> Click and drag to move across the entire title bar

- .gitpod.yml
Gitpod recently changed their default port visibility from public to
private (gitpod-io/gitpod#4548). This made it impossible for the front 
end to automatically connect to the trace server (see #415). Making the
port used by the server (8080) public solves this issue.
Fixes #415
> Make server port (8080) public

- README.md
Basic contribution guidelines could reduce repetition when onboarding new contributors. [See the changes on my branch](https://github.com/ebugden/theia-trace-extension/tree/contribution-guidelines#how-to-contribute-code) (screenshots below).
* Should these guidelines go in the repo wiki instead?
* Are the commit message guidelines too high a standard for our habits/needs?
* The linked step-by-step guide to contributing on GitHub (linked as [How to write and contribute changes](https://www.dataschool.io/how-to-contribute-on-github/)) is _excellent_.
[...]
> Add contribution guidelines to readme

- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/table-renderer-components.tsx
- Add a 'previous' button in the column search cells right beside the
'next' button
- Use keyboard short-cut SHIFT+ENTER to search previous event
fixes #412
> Support for searching for previous event in the Events Table

- packages/react-components/style/output-components-style.css
Fix misalignment between labels and rows in the Resources Status and Thread Status views.
In Chrome, the first line of the labels in the side bar of these views would not be aligned with the first row of the data. It would be located much lower in the view.
See attached images of the Resources Status view in Chrome and Firefox (added for comparison), before and after the fix.
Chrome before fix:
Chrome after fix:
Firefox before fix:
Firefox after fix:
> Fix misalignment between labels and rows

- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx
This PR fixes #411 by removing the bindings that were causing a `TraceViewerWidget` to be created when the layout was restored.
The `TraceViewerToolbarContribution` was `extending` `AbstractViewContribution` and implementing `initializeLayout`, but it doesn't need any `ViewContribution` functionality and should not try to open a widget on startup.
To test:
1. Open a trace and view some trace graphs.
2. You should have access to the same commands and toolbar items as on `master`.
3. Run the `View: Reset Workbench Layout` command.
4. You should not see any logs about widgets missing id's or inability to read `traceURI` of `null`.
> I see an error `Cannot read property 'annotationCategories' of null` logged by `trace-explorer-views-widget.tsx`, but I believe that that error is unrelated to …
> Do not open TraceViewerWidget when initializing layout

- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-tooltip-widget.tsx
Correct the error: "Each child in a list should have a unique “key” prop" for the else case.
> trace-explorer: correct a key error for the else case

- packages/react-components/src/components/trace-context-component.tsx
Changed the code to make the background color darker for the chart. It is now a shade of dark blue.
Contributes towards fixing #282
> Make chart background color darker (dark theme)

- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
Avoid a null pointer access if no annotation categories are provided. (e.g. with the flame chart)
Fixes front-end issue with 438
Signed-off-by: Matthew Khouzam <matthew.khouzam@ericsson.com>
> Null check annotation categories

- .github/workflows/publish-next.yml
This check added prevents the publish job to be run for forks of this
project.
> Only run publish-next build job for theia-ide/theia-trace-extension

- yarn.lock
Otherwise, for each yarn build the yarn.lock will be modified which
on the other hand will fail the publish to NPM.
> fix yarn.lock after the upgrade to Theia 1.17.2

- packages/react-components/src/components/xy-output-component.tsx
**Navigation implemented :** 
- **Zoom-in by following the mouse cursor :** "w","W" and "ctrl+mouse wheel up".
- **Zoom-out by following the mouse cursor :** "s", "S", and ""ctrl+mouse wheel down".
- **Zooming with range :** click right and drag.
-  **Panning left :** "a","A", "arrowLeft" and "shift+mouse wheel up".
-  **Panning right :**  "d","D", "arrowRight" and "shift+mouse wheel down".
Fixes theia-ide#389
**Here is the result**
> Implement navigation for XY charts

- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
We can zoom in/out and reste with the toolbar button centered on the selection.
We can zoom in/out with +/- in the keyboard centered on the selection.
If the selection is not visible the zoom will be done in the middle of the range we see.
Contributes towards fixing theia-ide#389
> We can zoom with +/- and reset the zoom 

- .gitpod.dockerfile
This PR is only a partial fix because Gitpod breaks in two places right now:
Details:
* Both issues (build fail, server connection fail) aren't present before the Theia version was upgraded.
* To observe the fontend not being able to connect to the server on Gitpod, you need to open this PR's branch (the extension doesn't build in Gitpod on the most recent version of master).
Commit a3a4002 "upgrade to Theia 1.17.0" in PR theia-ide#461 upgraded the version
of Theia used by the trace viewer extension. The new version of Theia
now requires keytar. This new dependency is missing in the gitpod setup
so the extension build fails in gitpod.
Update gitpod setup to install keytar (dependency) and fix gitpod
build.
> Partial Gitpod fix: Add keytar (new Theia dependency)

- packages/react-components/package.json
- yarn.lock
React widget re-ordering fails with the new version of react-grid-layout.
This is a temporary fix to address that issue.
fixes #495
> Temporary fix for react-grid-layout issues

- packages/react-components/src/components/xy-output-component.tsx
We can now zoom in/out with i/k.
Pan left/right with j/l.
> Add shortcut IKJL for XY chart

- examples/browser/package.json
- examples/electron/package.json
- lerna.json
- packages/base/package.json
- packages/react-components/package.json
- theia-extensions/viewer-prototype/package.json
- yarn.lock
This pull request provides commits done for the v0.1.0 release of `theia-traceviewer`, `traceviewer-base` and `traceviewer-react-components` to NPM .
The release builds used `timeline-chart` `v0.2.0` and `tsp-typescript-client` `v0.3.0`.
The last commit then will make sure that version next of these libraries are pulled-in during a build. 
Once this pull-request is merged I'll upload the tag `v0.1.0` on the commit with message `v0.1.0`.
> Release activities for v0.1.0

- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/style/output-components-style.css
Some views weren't able to display any data after the completion of the trace's analysis.
The problem was due to the fact that some provided models are empty server side because
they were no relevents trace events to display.
We choose to display a message indicating that there are no data to display in those cases
and update the state of the analysis client side. It will allow a better clarity of the user
experience.
Fixes #406
Signed-off-by: Jeff Godonou <jeffalecgodonou@gmail.com>
> Show view message when there is no data to provide

- packages/react-components/src/components/xy-output-component.tsx
We can select interval with shift-click.
**Here is the result :**
Fixes #439.
> Add the shift-click selection interval in XY chart

- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
We can now zoom with +/- or =/_ in timegraph and xy chart.
> Add zoom shortcut +/- for TIMEGRAPH and XY CHART

- packages/base/src/signals/signal-manager.ts
- packages/react-components/src/components/trace-context-component.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx
Initially the zooming capability was only supported for time graphs and it made somewhat sense to reference 'timegraph' in the names. However, after supporting it globally it's better to use generic names.
> Rename signals for zoom-in, zoom-out & reset zoom and related methods

- packages/base/src/utils/time-range.ts
- packages/react-components/src/components/data-providers/tsp-data-provider.ts
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
- yarn.lock
Use type 'bigint' for all variables that are timestamps or durations.
Rename TimeRange.getstart() to getStart().
The minimum view range in XY chart and toolbar button zooming is set to
2 ns, to be able to zoom out of it and to always have at least one time
axis tick fully visible.
Fixes Issue #41
> Use BigInt for timestamps

- packages/base/src/experiment-manager.ts
In the experiment manager, in updateExperiment() method, unconditionally
fetch the experiment from the trace server even if the experiment does
not yet exist in the experiment manager.
Fixes #547
> Unconditionally fetch experiment after application restart

- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
- packages/react-components/style/trace-explorer.css
fixes #507
Among all available views, if there is a text-overflow for name or description, the extra letters are replaced with ellipses.
When the width of the sidebar changes, the ellipses will be replaced with letters until the end of the string.
Also, if the mouse hovers on a view, the tooltip will display the view name and view description simultaneously.
Signed-off-by: yining wang <yining.wang@ericsson.com
>
> Add overflow ellipses and tooltips to Available Views list

- README.md
Add instructions on how to download and use the app.
Related to #352 #387
Motivation: Currently, users need to compile the Trace Viewer from source to view their own traces. To avoid the time-consuming dev setup and compilation we now offer a downloadable package (electron desktop application + trace server).
> Update README for packaged app

- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
All latency scatter XY charts have in common that each series don't
have a common x axis in comparison to the Histogram which have multiple
series where each series have the same x values the same number of
y-values.
The theia-traceviewer currently doesn't have support of drawing such
scatter charts properly and should be hidden.
The data provider descriptor, however, doesn't provide a way to
determine if it's a xy-chart with common x-Axis or not, and hence it's
not possible to generically hide such graphs.
This PR hides such graphs based on the data provider ID, which contain
the string "scatter" in it the Trace Compass case all with
org.eclipse.tracecompass.internal.analysis.timing.core.segmentstore.scatter.dataprovider.
Even if this is Trace Compass server specific, it will improve
the …
> Remove scatter data providers (latency scatter charts)

- theia-extensions/viewer-prototype/src/browser/trace-server-preference.ts
fixes #355 
The format of trace-server preference is now consistent with other related settings.
Signed-off-by: Yining Wang <yining.wang@ericsson.com>
> Clarify trace server settings labels

- packages/react-components/style/trace-context-style.css
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx
Fixes #531 
Resize handlers are visible
> Output container resize handlers visible in dark theme

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/style/output-components-style.css
fixes #537
avoids title-bar texts being mixed and makes diagrams more readable
3 output views opened and resized to their min-height:
> Add overflow ellipsis and tooltips to output title-bar

- packages/react-components/src/trace-explorer/trace-explorer-opened-traces-widget.tsx
- packages/react-components/style/trace-explorer.css
Fixes #336 
Remove button appears on hover
When window is made smaller the remove button would still appear
Clicking on remove button deletes the trace, does the same as right-click->'Delete Trace'
> Add ability to remove trace sets from Trace Explorer

- packages/react-components/src/trace-explorer/trace-explorer-opened-traces-widget.tsx
- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/theia-trace-explorer-opened-traces-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/theia-trace-explorer-views-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
fixes #489 
- When no trace tabs are open the available views section is empty:
Fix:
- Whenever a trace tab is closed fire a signal to trace-explorer-views-widget which checks the number of open tabs. If none, it will clear available views
- Then update available views for the selected experiment only if trace tabs are open
> Ability to clear list of analysis when no trace is selected (and open)

- package.json
- yarn.lock
This fixes the occasional build failure "/bin/sh: 1: tsc: not found"
> Add typescript to devDependencies in main packages.json file

- packages/react-components/src/trace-explorer/trace-explorer-opened-traces-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-commands.ts
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-contribution.ts
fixes #277
'Delete trace' renamed to 'Remove trace' to make it consistent with the remove traces tooltip
> Rename opened traces context menu delete command

- theia-extensions/viewer-prototype/src/node/trace-server-service.ts
It is often easy to write JS code that works in general cases, but miss corner cases... Especially with the process API which I believe was designed to be the most painful thing to use.
Some quirks include:
- `pid` is `undefined` iff Node couldn't actually spawn the process,
- `childProcess.exitCode` or `childProcess.signalCode` are set when the process exits,
- `childProcess.pid` can outlive the process, so issuing a kill on it after the process actually exited may end up killing another process that ends up inheriting the same `pid` some time later.
There were some code oddities like ``spawn(`${path}`, ...)`` which most likely was some kind of workaround around the fact that `path` can be `undefined`... But in such a case it would try to do `spawn('undefined', ...)` which doesn't make …
> improve the trace server spawning logic

- packages/react-components/src/components/utils/filtrer-tree/__tests__/__snapshots__/entry-tree.test.tsx.snap
- packages/react-components/src/components/utils/filtrer-tree/__tests__/__snapshots__/table-row.test.tsx.snap
- packages/react-components/src/components/utils/filtrer-tree/checkbox-component.tsx
- packages/react-components/src/components/utils/filtrer-tree/table-row.tsx
Replace spans with divs in first column of filter tree. Use flexbox to
create fixed width indentation box containing an optional right-aligned
expand/collapse button. Remove unnecessary padding in all buttons.
> Fix filter tree alignment

- packages/react-components/src/components/utils/filtrer-tree/sort.tsx
Right now the sorting is done using string sorting. If the data in the
columns are numbers, then number sorting should be used. Moreover,
some known string formatting can be reversed to extract the number and
do a number comparison. For example, some data providers provide columns
with duration, where the value is formatted to show 'ns' for nanosecond,
'us' micro-second and so on. Other example, are percentages shown.
The tree of the CPU usage view when using the Trace Compass trace server
is good example for different columns and formatting.
Note that this implementation is a temporary solution until the TSP and
server back-end is augmented to provide a different mechanism to
support sorting.
fixes #577
> Provide front-end sorting of trees for based on the column

- packages/react-components/src/components/timegraph-output-component.tsx
- yarn.lock
Support easier navigation in resources table by double-clicking a state to zoom into it
- Depends on https://github.com/theia-ide/timeline-chart/pull/169
- Width of element occupies the viewRange when double-clicked
Example:
> Ability to double-click states in Timegraph views

- packages/react-components/src/trace-explorer/trace-explorer-opened-traces-widget.tsx
fixes #599
I think in opened traces widget the default value for selectedExperimentIndex should be -1 so that it does not select the first experiment by default (index 0) when the component is initialized.
> Available views cleared when browser refreshed

- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-placeholder-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-commands.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx
fixes #193 
- Button added to the 'Opened Traces' widget header to allow opening additional traces. Button appears when mouse is hovered over widget
- In my approach I'm emitting a new signal when button is clicked, but I can reuse one of the existing signals instead
Named button tooltip "Open New Trace" because I think it differentiates from the context menu "Open Trace" command:
Unable to add '+' to the icon because theia commands accept a single iconClass param and I couldn't find a way to stack multiple icons in one element. We can upgrade font-awesome to v5 to get access to a folder-plus icon
> Add intuitive way to open additional traces

- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
Data sets with scattered points, like the "latency vs. time" view, are
now plotted in a scatter chart. The type of data set is defined by the
string "scatter" in the output id.
Each point of the data set can be displayed individually (scatter) or
connected by a line.
This pull request replaces
https://github.com/theia-ide/theia-trace-extension/pull/399.
Contributes towards fixing #45.
https://user-images.githubusercontent.com/88502808/145233812-bfc5f865-9e18-4851-9103-79ab6282b308.mov
> Scatter chart for latency vs. time views

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/abstract-tree-output-component.tsx
- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/style/output-components-style.css
Since the timegraph-output-component creates two trees that each have
their own scrollbar, remove the scroll overflow from the parent
output-component-tree.
Add scrollable wrapper to the xy-output-component and
datatree-output-component trees. Make the timegraph-output-component
wrappers scrollable.
Set the main-output-component overflow to hidden to prevent the
timegraph-output-component markers tree from overflowing when the output
area is too small.
Remove the tree scroll synchronization from the parent class
AbstractTreeOutputComponent and instead add it to the only tree that
needs it, the timegraph tree.
Fix tree width calculation in AbstractTreeOutputComponent.
Fix markers layer height calculation to ignore scrollbar height when the
tree is collapsed.
Remove filler row from markers …
> Fix output component scrolling and layout

- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/utils/filtrer-tree/__tests__/__snapshots__/entry-tree.test.tsx.snap
- packages/react-components/src/components/utils/filtrer-tree/__tests__/__snapshots__/table-row.test.tsx.snap
- packages/react-components/src/components/utils/filtrer-tree/column-header.tsx
- packages/react-components/src/components/utils/filtrer-tree/table-cell.tsx
- packages/react-components/src/components/utils/filtrer-tree/table-header.tsx
- packages/react-components/src/components/utils/filtrer-tree/table-row.tsx
- packages/react-components/src/components/utils/filtrer-tree/table.tsx
- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/style/output-components-style.css
Add resizable property to ColumnHeader model.
Add a resize handle to each resizable column header cell.
Add listeners to resize columns when the handle is dragged, and reset to
preferred column width when the handle is double-clicked.
Add filler column to make table-tree extend to full container width.
Change the table display, styling, borders, and header color.
Make all output component trees use the same base table-tree styling
with only timegraph-tree adding some specific styling overrides.
> Make table-tree columns resizable

- packages/react-components/src/components/utils/filtrer-tree/__tests__/__snapshots__/entry-tree.test.tsx.snap
- packages/react-components/src/components/utils/filtrer-tree/__tests__/entry-tree.test.tsx
- packages/react-components/src/components/utils/filtrer-tree/filter.tsx
- packages/react-components/src/components/utils/filtrer-tree/tree.tsx
- packages/react-components/style/output-components-style.css
Add resize observer on first column header to synchronize filter width.
Remove text message on empty filter result as this disrupts the observer
and prevents synchronization after the non-matching filter is removed.
> Make filter width match first column width

- packages/react-components/src/components/trace-context-component.tsx
- yarn.lock
This allows it to create gridlines on rounded absolute times.
> Set offset in time graph unit controller

- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/style/output-components-style.css
While the data tree component is loading data, display an "analysis
running" message in the middle of the component.
The data tree components are still hidden, as metioned in #598.
Contributes to #144.
> Display loading message on data tree components

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/abstract-tree-output-component.tsx
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/style/output-components-style.css
* **Commits 1-4:** Code and styling cleanup for "no results" message added by #447 (with my limited HTML knowledge)
* **Commits 5-7:** For the XY, Timegraph and Table output components, add message for when the analysis fails:
* Output status is always set: When the TSP response is bad, and in all cases when the TSP response is good
* "Analysis failed" message displays when the status is FAILED
Because there's a lot of cleanup and changes in several files I recommend looking at the commits separately.
Currently, if the analysis fails (i.e. outputStatus is FAILED) then the
analysis's view panel never updates and shows "Analysis running" forever
even though the server has responded.
Show a message to tell the user the analysis has failed.
Contributes towards fixing #460
Signed-off-by: Erica …
> XY Charts, Timegraph, Table: Display message when analysis fails

- package.json
- yarn.lock
| Package | Current | Updated to |
| --- | --- | --- |
| @theia/cli | 1.10.0 | 1.21.0 |
The update resolves Dependabot alerts for the following packages:
- color-string;
- glob-parent;
- underscore;
- is-svg;
- yargs-parser;
- serialize-javascript.
> Update @theia/cli dependency to version 1.21.0

- yarn.lock
Without the change the yarn.lock is being update at every build and
it makes publishing to NPM fail.
> Update bigint dependencies in yarn.lock

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/abstract-tree-output-component.tsx
- packages/react-components/src/components/null-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/components/utils/__tests__/time-axis-component.test.tsx
- packages/react-components/src/components/utils/__tests__/time-navigator-component.test.tsx
- packages/react-components/src/components/utils/output-component-style.ts
- packages/react-components/src/components/utils/time-axis-component.tsx
- packages/react-components/src/components/utils/time-navigator-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/style/output-components-style.css
- yarn.lock
Add a sash between the tree and the chart. For XY chart insert the sash
between the Y-axis and the chart.
Add mouse handling to the sash to call the setSashOffset() callback when
moving the mouse while the sash is clicked, to propage the new sash
offset to all output components.
Refactor the width handling to use handle width, sash offset and sash
width to compute the tree width and chart width.
Add hover color and cursor to the sash.
> Add horizontal resize sash to output components

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/abstract-tree-output-component.tsx
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/style/output-components-style.css
when analysis results are empty.
For all components, display message in the main chart area to keep
visual consistency.
Other details:
* Make CSS class name general since it is being used for several messages
now.
* Change CSS properties to consider text displayed on multiple
lines. The manual margin-top ajustment is a hack that only works for
single line messages.
Generalization of PR theia-ide#447
Fixes theia-ide#406
> Table, Timegraph, XY Chart: Display "no results' message

- .gitpod.yml
The server has been managed automatically (start/stop) since PR #298.
Removing the manual trace server start reduces possible sources of bugs
because of interference with the manual and automatic server
management.
----
Submitting as a draft since I'm not sure if changes should be made to 
the [export statements](https://github.com/ebugden/theia-trace-extension/blob/d8c5048a56eb4d0d20a15e6fc6136335635f4c92/.gitpod.yml#L22) a couple lines below:
`command: >
export GITPOD_URL=$(gp url 8080) &&
export TRACE_SERVER_URL=$(echo "$GITPOD_URL/tsp/api")`
Are the export statements defining on which port the trace server should start?
Or specifying which port the server was manually started on?
----
Fixes #319
> Cleanup: Remove manual trace server start in gitpod

- packages/react-components/style/trace-explorer.css
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-keyboard-shortcuts/charts-cheatsheet-component.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-keyboard-shortcuts/essential-shortcuts-table.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-keyboard-shortcuts/select-shortcuts-table.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-keyboard-shortcuts/time-graph-navigation-shortcuts-table.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-keyboard-shortcuts/zoom-pan-shortcuts-table.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-commands.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-commands.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx
'Trace Viewer Keyboard and Mouse Shortcuts' dialog:
Dialog can be triggered by:
1) Clicking info icon that appears in toolbar when a time-graph or xy-chart is opened:
2) Using Theia's 'find command' search:
3) Using keybinding 'CTRL/command + F1'
> Add dialog for Trace Viewer Keyboard and Mouse Shortcuts

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/abstract-tree-output-component.tsx
- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/null-output-component.tsx
- packages/react-components/src/components/table-output-component.tsx
Messages are now handled in the abstract output component so less code is required in each output component.
When error messages are handled in each component rather (than by the
parent class), it is easy to forget to handle these errors when
implementing new output components. Handling errors in the parent class
makes these bugs less likely.
"No results" message: Instead of needing to remember to call the
function in each output components the abstract class structure imposes
that every output component implement a check for empty results (and
displaying the message is handled by the parent class).
Analysis failed message: The developper still needs to remember to set
the output status to failed when implementing new output components.
This change does not help with remembering to do …
> Data Tree: Add "analysis failed" and "no results" messages

- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
These tooltips behave as in the line charts: when the mouse stops moving for a
couple of seconds the tooltip is triggered.
If there are points close to the mouse pointer, the tooltip displays a
list with the closest point of each series. If the points are too far, the
tooltip is not shown.
The tooltip displays the timestamp that corresponds to the position of
the mouse, and y-value of the closest points.
This commit also enables the scatter plots, since the two issues that
were blocking their release (bug about lack of precision and the absence
of tooltip) have been resolved.
https://user-images.githubusercontent.com/88502808/150555054-b6efa227-0e23-4c0e-a3ef-0ac72edecd72.mov
> Enable tooltips for scatter plots.

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/null-output-component.tsx
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/components/utils/timegraph-container-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
- packages/react-components/style/output-components-style.css
- theia-extensions/viewer-prototype/package.json
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
- yarn.lock
This PR has changes for the following features suggested by @PatrickTasse in #311
- When clicking on an analysis in the Available Analysis list, in the selected trace tab, the analysis is scrolled into view and given keyboard focus. User can click tab to access the tree and chart of the focused graph.
- The trace tab should be scrolled to make that analysis visible, whether it is being opened for the first time or if it was already created previously.
- When clicking on an analysis title in the trace tab, keyboard focus should be the analysis' graph/chart region. This is indicated by a blue focus border, allowing the user to directly use keyboard interactions/shortcuts
fixes #414
- If a View that is already open is selected in the sidebar, the View's title area should pulse to temporarily …
> Set keyboard focus on graph/table when selecting an analysis

- packages/react-components/src/components/abstract-tree-output-component.tsx
- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/null-output-component.tsx
- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
- packages/react-components/style/output-components-style.css
**Current Behavior**: Labels in trace viewer and trace explorer can be selected with mouse.
**Expected Behavior**: Selecting the text in trace viewer and trace explorer (other than tooltip) should be restricted. Current behavior doesn't have good UX
> Selecting device names/labels shoudn't be allowed

- packages/react-components/src/components/trace-context-component.tsx
Disabled the browser's context-menu for the entire TraceContextComponent, which effects the area highlighted in blue:
There are still areas in the extension where we can access the browser's context-menu: 
- Empty space under "Opened Traces"
- Empty space under "Item Properties"
- Empty space next to Trace Tabs (near top)
If we want the right-click disabled there too, we can move this to a higher-level component.
Fixes: #634, #635
Signed-off-by: William Yang william.yang@ericsson.com
> Remove context menu from TraceContextComponent

- .vscode/launch.json
- This PR starts with fixing the existing launch configuration that runs specific tests.
- Follows a second commit that adds a new launcher, this time to run every Jest test.
- Each commit has a message listing the steps for how to test these.
> Launch: adjust the Jest-based configuration(s) running tests in VS Code

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/abstract-tree-output-component.tsx
- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/null-output-component.tsx
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/components/utils/__tests__/time-axis-component.test.tsx
- packages/react-components/src/components/utils/__tests__/time-navigator-component.test.tsx
- packages/react-components/src/components/utils/output-component-style.ts
- packages/react-components/src/components/utils/time-axis-component.tsx
- packages/react-components/src/components/utils/time-navigator-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
Calculate AbstractOutputComponent's main area width based on props instead of client width that isn't updated yet during a resize.
Ensure minimum of 0 for tree width and chart width.
Remove unnecessary paddingRight in ResponsiveGridLayout's style.
Add marginRight to TimeAxisComponent and TimeNavigatorComponent to account for scroll bar padding.
Remove arbitrary initial width in TraceContextComponent constructor.
Make handleWidth, yAxisWidth and sashWidth optional in OutputComponentStyle.
Move default handle width constant to AbstractOutputComponent. Add getter for handle width.
Move default Y-axis width and sash width constants to AbstractTreeOutputComponent. Add getters for Y-axis width and sash width.
Rename sash offset to chart offset.
Make chart offset include the handle width, Y-axis …
> Fix chart width on resize and cleanup related code

- theia-extensions/viewer-prototype/src/node/backend-file-service-impl.ts
On Windows, Theia returns an invalid file path when opening traces. The invalid file path begins with a forward slash **/**. For example, the path **C:/** will become **/C:/**. This prevents the trace extension from opening trace files. This is a known Theia issue. More on the issue can be read [here](https://github.com/eclipse-theia/theia/issues/8098).
This commit resolves temporarily this issue by using [FileUri](https://eclipse-theia.github.io/theia/docs/next/modules/core.fileuri-1.html) to convert the original file path returned by Theia to a platform specific path. This will allow the trace extension to open traces on Windows. 
Signed-off-by: Hoang Thuan Pham &lt;hoang.pham@calian.ca&gt;
> Fix invalid path on Windows when opening traces

- doc/adr/0002-GraphQL.md
Add the currently known items to that section,
- which then leads to the following sections about actions and the query parameters.
- These are to be filled through follow-up commits, scope wise.
> GraphQL ADR: initialize the 'filtering' section

- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/style/trace-context-style.css
Implement different visual containers for views that have an X axis and those that don't
Changes Made:
- View is arranged into charts that use the X-axis (TimeAxis & TimeNavigator components) and those that don’t.
- Sizes and orders of charts are preserved when views are added or removed
- The close button is accessible when only a single view that does not spawn the time-axis is open
Notes:
- I've added some commenting for now to explain my implementation
- I feel that the runtime is a bit high, would like some suggestions on how I could optimize
fixes #287
fixes #648
fixes #618
> Split X-axis views and non-X-axis views

- packages/react-components/src/components/__tests__/__snapshots__/table-renderer-components.test.tsx.snap
- packages/react-components/src/components/__tests__/table-renderer-components.test.tsx
- packages/react-components/src/components/table-renderer-components.tsx
Created some unit tests for user-defined functions and components used in the events table. Was unable to create comprehensive tests for TableOutputComponent since its entirely built upon the AG-Grid library, and snapshot testing does not show the rendered HTML of AG-Grid. Another way to test TableOutputComponent could be to stub api calls made by the component to fetch table data and check if the internal state of the component (table columns & lines) updates. I was unable to mock tsp-client api calls or stub responses since jest could not reference the requests being made by the component's methods. But I believe we can later add to this test once we figure out a way to do so. Also included snapshot and unit tests for TableRendererComponents which are used by TableOutputComponent …
> add unit tests for the events table

- packages/react-components/src/components/xy-output-component.tsx
In componentDidUpdate(), do not trigger a xy request if the previous
outputStatus was running, only trigger it if the outputStatus changed.
This will trigger it only once, when the analysis is completed.
Fixes #691
> Prevent unnecessary xy requests while analysis is running

- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/utils/filter-tree/tree.tsx
Show statistics for selected region in datatree-output-component
In the datatree-output-component, a subtree labeled 'Selection' is shown whenever there is a region selected. When no region is selected, hide the row:
> Implement statistics for a selected area in the chart

- doc/adr/0002-GraphQL.md
- Each PR commit describing each aspect, per their respective amend(s).
- This ADR still has a few open questions in its text, backlogged for other (eventual) PRs.
> GraphQL ADR: detail potential Java server library alongside optional client ones; fix left-over questions

- packages/react-components/package.json
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-commands.ts
- yarn.lock
Currently, the trace extension uses the ![image](https://user-images.githubusercontent.com/92533264/153945276-909063ea-6805-4bf6-8969-13e0006b9ebf.png) icon for the open trace button. This can be confusing for users, since they can see the action as closing the current trace and opening a new one. The expected understanding of this action is opening a new trace along side the old ones. This commit updates the icon of the open trace button to ![image](https://user-images.githubusercontent.com/92533264/153945389-477dbcd3-d1ef-4580-8bc4-f53cef604f4c.png) to avoid this confusion.
Signed-off-by: Hoang Thuan Pham <hoang.pham@calian.ca>
> Update open trace icon to avoid confusion

- packages/react-components/src/components/trace-context-component.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
Implement StatefulWidget in the TraceViewer class and hook into the StoreState and RestoreState methods, which preserve data in LocalStorage.  This works with browser and electron.
Currently only storing outputDescriptors (opened views), but can built upon for future features.
Handled an edge-case bug where timeline-chart components crashed when state.style.width = 0 in TraceContextComponent.  This also stops unopened experiment tab views from loading
on startup.
> Persist opened views on page refresh

- doc/adr/0005-tsp-update-experiment.md
> Add ADRs about updating of experiments as part of the TSP

- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
Using throttling to prevent flooding the trace-server with requests when xy chart is updated. Fixes the issue of delayed movement during panning, as well as the misalignment between charts. I decided to use throttle instead of debounce since debounce would trigger only when the user stops panning, whereas throttle invokes the update once every 500ms. I've attached a video showing the performance of a panning operation, you can compare it to the video in #470 that shows a 37 second delay. Please suggest if there's any other performance optimizations for this scenario or tricks to achieve smoother pan animation.
https://user-images.githubusercontent.com/92893187/159570352-fd96001c-3810-482a-ae68-0f68d982273e.mp4
fixes #470
fixes #453
Signed-off-by: hriday-panchasara …
> Throttle xy-chart data update

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
Users expressed frustration that they would start interpreting the data and then additional chart elements would suddenly appear. Therefore in timeline-chart and xy-charts when data is being fetched due to user interactions (toggle tree, zoom and pan) show a loading spinner next to the title bar.
Examples:
Fixes #649
> Indicate when data is still loading

- packages/react-components/src/components/xy-output-component.tsx
Zoom in into the xy-chart, press the control key and move the mouse with the left mouse button pressed to move the data of the xy-chart to the left or the right.
Lifting the control key while dragging does not stop the drag.
Fixes #637.
> Move xy-chart's data with CTRL + mouse drag

- README.md
- packages/base/README.md
- packages/react-components/README.md
- theia-extensions/viewer-prototype/README.md
The repository has been moved to the Eclipse cdt-cloud project and is now located under the eclipse-cdt-cloud GitHub organization. Replace theia-ide with eclipse-cdt-cloud references in all relevant README.md files. 
Fix incorrect links in the README.md files.
Change links to inline references for better re-use references and for better readability of source file of the root-level README.md. 
> Clean-up readme for the move to eclipse-cdt-cloud and references

- packages/react-components/src/components/xy-output-component.tsx
Provides the structure to plot bar charts when this type of chart becomes available.
To test it, set
```js
private isBarPlot = true;
```
in `xy-output-component.tsx` file. Then open an xy plot like "CPU usage".
> Bar chart code base for xy charts

- packages/react-components/src/components/data-providers/tsp-data-provider.ts
- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
- yarn.lock
Use the new QueryHelper methods for requested time range queries instead
of requested times array.
Signed-off-by: Patrick Tasse <patrick.tasse@gmail.com>
> Use time range queries for states, annotations, arrows and xy

- doc/adr/0002-GraphQL.md
Now that the proposal is done reviewing internally, close it for the
time being while documenting this decision.
> GraphQL ADR: Close current proposal after reviewed

- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
Before this change, opening two traces then moving one in its own panel
caused an infinite focus loop between these two. That event loop seemed
to have been caused by onAfterShow firing an extra event during that
move action.
Removing that overriding method in TraceViewerWidget fixes that event
loop, lending the moved trace tab in focus as expected (in its own
panel). No evidence of requiring that method in other cases was found.
Fixes #736.
> trace-viewer: Remove onAfterShow causing event loop

- packages/react-components/src/components/data-providers/tsp-data-provider.ts
- packages/react-components/src/components/timegraph-output-component.tsx
- yarn.lock
Fetch visible rows only
Add support for rowProvider which returns the full list of row ids.
Add support for rowIds parameter in dataProvider interface.
Add support for undefined row model in rowStyleProvider interface.
Update for rename of getElementById() to getStateById().
Allow the selectedElement to become undefined if the new selection
cannot be found.
Signed-off-by: Patrick Tasse <patrick.tasse@gmail.com>
Fix use of TimeGraphArrow sourceId and destinationId
The sourceId and destinationId should be the row id of source row and
destination row. But it is used as the index of the source and
destination rows in the full list of rows.
Change to use the sourceId and destinationId properly. This requires
that the TimeGraphChartArrows layer receive the full list of row ids.
Signed-off-by: …
> Fetch visible rows only

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/style/output-components-style.css
Export datatree-output-component to csv
- Expanded options menu to show 'Export to CSV' in datatree-output-component. Aim is to add 'Export to CSV' options to table-output-component's options menu as well as pin/unpin option to abstract-output-component's (Base class) option menu
- Trace name given to downloaded file
> Export datatree outputs to csv

- .vscode/launch.json
- packages/react-components/src/components/xy-output-component.tsx
- yarn.lock
1. Reverse negative if statement.
2. Rescope yValues/pairs locally.
3. Deserialize for isScatterPlot.
4. Add urlFilter to the attach-chrome config.
Each commit message should have their necessary details.
> xy-output-component: Deserialize for isScatterPlot

- packages/base/src/signals/signal-manager.ts
- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/style/output-components-style.css
- Add Ability to pin views to the top of the layout so that they stay visible when scrolling
- Current implementation is to allow pinning only one view at a time
- View is scrolled into focus when pinned/unpinned
- Pinned view persists when page refreshed
- Added additional resize handlers to pinned view in case height exceeds page length
> Ability to Pin Views

- packages/react-components/src/components/utils/filter-tree/__tests__/__snapshots__/entry-tree.test.tsx.snap
- packages/react-components/src/components/utils/filter-tree/filter.tsx
- packages/react-components/style/output-components-style.css
This commit makes the text box for filter in the filter-tree more noticeable and recognizable as a text box by adding rounded borders and a filter-icon.
Resolve: [Issue #662](https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/622)
> Improve filter text box discoverability

- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/components/utils/__tests__/time-axis-component.test.tsx
- packages/react-components/src/components/utils/time-axis-component.tsx
Currently, the ticks of the time axis are displayed above the time values, which do not make sense UI-wise since graphs are displayed under the time axis. This commit moves the ticks to under the time labels by specifying the tickPosition configuration parameter of the TimeAxisComponent.
Resolve [Issue 775](https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/755). Need to be merged after [Issue 203](https://github.com/eclipse-cdt-cloud/timeline-chart/issues/203) is resolved.
> Move the ticks of the time axis to below the time values

- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/utils/filter-tree/utils.tsx
Select corresponding chart components from the events table.
Clicking on a line in the events table will cause a chart like "Thread
Status" to scroll vertically to the row which has the element that
corresponds to the clicked event.
For each line in the timegraph tree, parse the metadata in the
TimeGraphEntry received from the server and try to find matches with the
key / values pairs of the clicked event. It will select the entry which
has the most matches.
When selecting an event using the search capability in the events table
broadcast the event details to other charts to select corresponding
chart component.
When using the keyboard to select an event, broadcast the event details
to other charts to select corresponding chart component.
Add support for arrow up/down key selection of …
> Select chart components from a selection in the events table

- packages/react-components/src/components/utils/filter-tree/__tests__/__snapshots__/entry-tree.test.tsx.snap
- packages/react-components/src/components/utils/filter-tree/filter.tsx
- packages/react-components/style/output-components-style.css
Currently, the filter icon of the filter text box stays fixed at the top left of the filter tree, even when the filter text box is out of sight when users scroll down the tree. This commit fixes this issue by setting the position css property of the parent div of the filter text box to relative, so that the filter icon is positioned relatively to the parent container and stays attached to the filter text box.
This bug is related to [PR 759](https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/759).
> Fix css positioning for filter text box icon

- packages/react-components/src/components/table-output-component.tsx
During the developpment of the segment store table data provider this issue was found.
In fact the vertical scrollbar was not adjusted to show the real size of the table.
In this PR, the issue is resolved by setting the size of the table to be the same as the number of elements displayed in the table.
> Fix theia-trace-extension table vertical scrollbar

- packages/react-components/src/components/utils/xy-output-component-utils.tsx
In line charts when the view range only has 0 for y values the line is kept at the bottom
[Screen Recording 2022-07-19 at 10.50.38 AM.webm](https://user-images.githubusercontent.com/92893187/179798600-f015b8e5-341f-436c-a5e2-cda1a5b6cce9.webm)
fixes #780
> XY plots put zero at the bottom

- packages/base/src/signals/signal-manager.ts
- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/abstract-xy-output-component.tsx
- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/components/utils/filter-tree/utils.tsx
- packages/react-components/src/components/xy-output-component.tsx
- This is an improvement of the feature in PR #739 
- When a view is pinned/unpinned it is re-rerendered onto the layout as it is moving to a different container. This re-rendering does not happen when dragging views since they are re-arranged in the same container. So when a view is pinned/unpinned, the charts lose their state and the user has to redo the selections.
- This patch tries to persist the state of the view that's being pinned and unpinned. Luckily, we are able to pass the state of the chart as a payload when firing the signal to pin/unpin a view.
- This is being used by the xy-charts to pass the checkedSeries and collapsedNodes of the tree, and the timegraph-charts to pass the collapsedNodes and collapsedMarkerNodes.
- By doing so we ensure that the chart state stays the same …
> Persist state of view after pin/unpin

- packages/react-components/style/trace-explorer.css
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-placeholder-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-server-status-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-server-status.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-commands.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx
I found the following issues with the current server status indicator:
1) Status indicator is incorrect when the trace-viewer is started without connection to the server:
2) Status indicator is incorrect when toggling the trace-viewer left-hand panel (trace-explorer-widget):
When looking into the code, the connectionStatusListener defined in PR #671 works as expected, but it is not always able to modify the indicator through JavaScript. This might be because the indicator is not an icon but a Theia Command. Registering a toolbar command allowed us to place the icon in Trace Explorer widget's title bar, but the statusListener fails to always update the icon. A better contribution point would be to place the icon as a child of the Trace Explorer widget. The following is how the status …
> Fix issues with server status indicator

- packages/base/src/signals/signal-manager.ts
- packages/react-components/src/components/abstract-dialog-component.tsx
- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/abstract-xy-output-component.tsx
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/components/trace-overview-component.tsx
- packages/react-components/src/components/trace-overview-selection-dialog-component.tsx
- packages/react-components/src/components/utils/available-views-component.tsx
- packages/react-components/src/components/xy-output-overview-component.tsx
- packages/react-components/style/dialog-component-style.css
- packages/react-components/style/trace-explorer.css
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
Currently, the trace overview only works with the Histogram output. This commit adds a dialog that allows users to select different outputs for the trace overview.
This resolves issue #775.
> Add dialog to select output for trace overview

- packages/react-components/src/components/trace-context-component.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-keyboard-shortcuts/time-graph-navigation-shortcuts-table.tsx
Allows user to press z to zoom to current selection.
Adds relevant information to keyboard shortcut menu.
Fixes: #427 
> Zoom into selection range using z

- packages/react-components/src/components/trace-overview-selection-dialog-component.tsx
- packages/react-components/src/components/utils/available-views-component.tsx
- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
Currently, the trace-overview-selection-dialog-component and the trace-explorer-views-widget have some common code. This
commit refactors the common code by creating the reusable available-view-component. The prior two components will then call the later component and thus use the same code.
> Refactor available views component

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/style/output-components-style.css
Change CSS style of options-menu so that we can re-use theia styles for it:
fixes #751
> Improve options menu styling

- packages/react-components/src/components/abstract-xy-output-component.tsx
xy chart updates data model when size of parent component (trace-context-component) is changed
[Screen Recording 2022-07-21 at 11.05.33 AM.webm](https://user-images.githubusercontent.com/92893187/180261591-0270e757-adf0-47e1-ba8e-3edf91792912.webm)
fixes #726
> XY Chart refresh data model on resize

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/null-output-component.tsx
Fixes #808
Note: To test change the Trace Compass server back-end to return an unknown provider type in an output descriptor. This is how it will look like:
> Fix rendering of message about unsupported output type

- packages/react-components/src/components/abstract-xy-output-component.tsx
Replace throttle with debounce when handling xy chart update requests
> Debounce xy chart data update

- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-keyboard-shortcuts/charts-cheatsheet-component.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-keyboard-shortcuts/events-table-shortcuts-table.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
Helps fix #742
- The requested shortcuts described in #742 are implemented by default in all ag-grid tables: https://www.ag-grid.com/react-data-grid/keyboard-navigation/
- I added these shortcuts to the Keyboard Shortcuts menu to make them discoverable. I also added the following keyboard/mouse interactions:
- Select Multiple rows: 'Shift + click' or 'Shift + arrow up/down'
- Deselect rows: 'ctrl or meta key'
- In table-output-component I also noticed that 'space' is registered as a key interaction to replace multi-select with a single row, but was not sure how to describe it in the shortcuts menu as a user can single-click or use ctrl to remove multi-select
- Here's how the shortcuts menu looks now:
> Add Events Table Shortcuts to the Keyboard Shortcuts Menu

- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-commands.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
Add the ability to open the trace file picker dialog with a custom root path if needed
Fixes #811
> Toggle Open Trace File Picker with custom path

- examples/electron/package.json
- package.json
- packages/base/package.json
- packages/react-components/package.json
- theia-extensions/viewer-prototype/package.json
Update with the most up-to-date url the
package.json files in the project.
Probably was forgotten when migrating the
project to eclipse-cdt-cloud in github.
Signed-off-by: Francesco Robino <francesco.robino@ericsson.com>
> Update package.json to cdt-cloud url/homepage

- packages/react-components/src/components/datatree-output-component.tsx
Make 'export to csv' option work as expected in both browser and electron
Fixes #824
> Implement datatree-output-component csv export in electron

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/style/output-components-style.css
Titles of elements like charts, when too long, are cropped and display an ellipsis at the end of the text. On Safari browsers this ellipsis is not appearing.
Safari's `text-overflow: ellipsis` property works correctly, but when used in conjunction with `writing-mode: vertical-rl`, apparently it fails to display the ellipsis.
Fixes #764.
> Fix for title bar on Safari browsers

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/abstract-tree-output-component.tsx
- packages/react-components/src/components/abstract-xy-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/src/components/xy-output-overview-component.tsx
This commit creates a hamburger menu for the trace overview that will allow users to toggle the filter tree and select a different output view. The hamburger menu replaces the existing cog icon that is used for output source selection. A new state property is added to the AbstractTreeOutputComponent that allows showing and hiding the filter tree. The overview then toggles this state property.
Fix #787
> Toggle the filter tree for the trace overview

- theia-extensions/viewer-prototype/src/browser/trace-overview-binding.ts
- theia-extensions/viewer-prototype/src/browser/trace-overview-preference.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
Currently, the trace overview default view is hard-coded in the trace viewer. This commit allows users/developers to set an XY view as the default view for the trace overview (using its name).
Users can set the default view for the trace overview using the Preference UI (File > Preferences > Open Settings or Ctrl + ,).
Developers can also set the default view for a specific Theia build by adding the "trace Viewer.trace Overview.defaultView" property to the "preferences" object in the package.json file (see snippet below - similar to `trace-viewer.port`) of the build and indicate the name of the default view.
https://github.com/eclipse-cdt-cloud/theia-trace-extension/blob/38d4e175718746f368e2ba2e3669e76bdcd40ec9/examples/browser/package.json#L5-L15
Fixes #840.
> Add configurable default view for the trace overview

- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/table-renderer-components.tsx
This PR is made of these commits with more details in their respective commit messages:
1. Fix findMatchedEvent row 0 case.
2. Fix backward search upon index 0.
3. Fix selectStartIndex assigned to itself.
4. Wait for search before selecting.
5. Fix exception upon early Enter.
6. Reset navigating selection if new search.
7. Separate search and matching.
8. **Decrease debounce ms by 50x.**
**The latter (PR's head) commit** formally fixes #859.
> TableOutputComponent: Fix these search selection related cases

- packages/base/src/signals/signal-manager.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
Currently, the trace overview open signal is broadcasted to all opened traces which causes the overview to open in all trace tabs. This commit adds a traceId parameter to the function that opens the trace overview, so that the trace viewer can check and only open the overview for the current active trace tab.
Fixes #856.
Signed-off-by: Hoang Thuan Pham <hoang.pham@calian.ca>
> Fix overview opened in all trace tabs when using the toolbar button

- packages/react-components/src/components/utils/xy-output-component-utils.tsx
- packages/react-components/src/components/xy-output-overview-component.tsx
Currently, the zoom range is shown in the trace overview using an orange overlay. When the users want to select a range (indicated by a blue overlay), these two layers overlap and make it hard to distinguish them. This commit improves the color scheme for the zoom range by 1) remove the orange overlay of the zoom range and 2) use a grey overlay to indicate the part of the trace that is not zoomed.
Fixes #857.
Signed-off-by: Hoang Thuan Pham <hoang.pham@calian.ca>
> Improve color scheme for zoom range of overview output

- packages/react-components/src/components/data-providers/tsp-data-provider.ts
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/utils/timegraph-container-component.tsx
- yarn.lock
Syncs Theia-Trace-Extension with Viewport Implementation changes made to the Timeline-Chart repo.
Updates getData in TspDataProvider, viewRange changed to worldRange for clarity.
Removes logic for calculating viewRange overlap, which is now handled in the Timeline-Chart repository.
Requires Timeline-Chart branch: https://github.com/eclipse-cdt-cloud/timeline-chart/pull/213
Signed-Off-By: Will Yang <william.yang@ericsson.com>
> Viewport Implementation - Sync

- package.json
Download the plug-ins sequentially instead of parallel. This should avoid the failure "Download:plugins fails with 429".
see discussion:
https://community.theia-ide.org/t/download-plugins-fails-with-429/2659
> Workaround rate limitation issues with open-vsx

- packages/react-components/src/components/table-output-component.tsx
Ag-grid says tables with too many rows have problems because of the limitation of a div's size, which is defined by the browser (see https://www.ag-grid.com/javascript-data-grid/massive-row-count/).
In order to check what the limitation is, one has to set `debugFlag=true` in `table-output-component.tsx` and watch the console when a large table is loaded. Doing so in a computer with a small monitor (1920 x 1200 px, dpi scale = 1) heralds:
`AG Grid.RowContainerHeightService: maxDivHeight = 32,000,000`
If each row has a height of 32 px, that means the table will start presenting selection issues below the millionth row. In fact, we observed problems precisely with tables that large.
A browser on a larger monitor (5120 x 2880 px, dpi scale = 2) heralds instead:
`AG …
> Fixes large tables on high-dpi monitors

- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-commands.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
This new command takes a path to a trace directory and opens the trace in the trace viewer.
The use case is we have an extension that collects traces from target hardware, when that trace collection is complete we want to open it in the UI. Adding this new command allows us to open the trace in the viewer by passing the path to the new trace.
The alternative we considered was, in our extension, connecting to the trace server and issuing a tspClient.openTrace and then tspClient.createExperiment. While this does load the trace on the server, we still need a way for the UI to refresh. Rather the providing a new command to refresh the UI we propose this new command as it also saves us from duplicating all the work to interact with the tspClient.
> Add new command open-trace-with-path to open a trace with the given path

- packages/base/src/signals/signal-manager.ts
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/trace-explorer/trace-explorer-properties-widget.tsx
- packages/react-components/src/trace-explorer/trace-explorer-tooltip-widget.tsx
- packages/react-components/style/trace-explorer.css
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/theia-trace-explorer-opened-traces-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/theia-trace-explorer-properties-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-tooltip-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
Changes made:
- Implemented a properties widget in react-components
- Change theia implementation to use the widget from react-components
This will move the properties widget to the react-components npm package, so it can be used by both the theia extension and vscode extension.
Signed-off-by: Neel Gondalia ngondalia@blackberry.com
> Created a widget for properties view in react-components

- .gitignore
Currently there is a git rule to ignore all `lib/` folders in the project. But some sub-project might have lib folders that have to be commited.
One solution would be to add exceptions to the `.gitignore` file as in `!doc/lib/`. This would allow git to commit the "doc/lib/" folder, but for this to work the exception has to be added after the excluding rule, as in:
```
lib/
!doc/lib
```
If the exception comes before the rule, it is overruled. This is a problem because the sorting rule applied to .gitignore files automatically moves all exceptions (lines starting with "!") to the top of the file.
To avoid this problem for the case of the "lib/" folders, this PR replaces the `lib/` rule with more specific ones, so that no extra exception rules for lib folders are necessary.
Signed-off-by: …
> Use specific rules for lib folders in gitignore

- packages/react-components/src/components/abstract-xy-output-component.tsx
- yarn.lock
If 'isDefault' flag is set for an XY entry, then check it in the tree and fetch its XY data to fill the XY graph once the analysis is complete.
- Fixes #786 
- Requires to build: https://github.com/eclipse-cdt-cloud/tsp-typescript-client/pull/70
- Corresponding: TSP specitication: https://github.com/eclipse-cdt-cloud/trace-server-protocol/pull/85
- Contributes to https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/786
Example back-end implementation:
- https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/199322
- https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/199323/1
- https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/199324
> Use new TSP APIs for XY entries to check for default entries

- packages/react-components/src/components/data-providers/style-provider.ts
Add a null check for values in the OutputElementStyle to avoid an exception if the values are not set, i.e. not send by the backend.
> Make StyleProvider more robust

- packages/react-components/src/components/abstract-tree-output-component.tsx
- packages/react-components/src/components/abstract-xy-output-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/src/components/xy-output-overview-component.tsx
- packages/react-components/style/output-components-style.css
Changes the overview chart and the timegraph chart to display data as it is being loaded.
Changes are more notable in the overview. For the timegraph chart, even though the "analysis running" message was replaced by the direct display of data being loaded, its duration is normally short.
To see its effect, one should set the overview to open the "CPU Usage" analysis (set on preferences), because the "CPU Usage" displays a chart before having the user to select any series.
The effect is evident when a new large trace that makes several calls to the `fetchTree` endpoint is opened. After it is loaded, the result of the calls is cached and all charts open quickly.
Other charts like the "Disk I/O View" do not show the data as it is being loaded because they need the user to make a selection …
> Display data as it is made available

- packages/react-components/src/components/trace-context-component.tsx
With this change only 0.25 times (instead of 1.0) of the view range is cached on the before and after of the window range. This reduces the amount of data to be fetched and managed down. This will improve the performance of the timeline-chart when, for example, zooming.
Horizontal panning inside the world range is still available due to the cached data.
Fixes #912
> Reduce timeline-chart cache by reducing worldRangeFactor to 0.25

- packages/react-components/src/components/__tests__/table-renderer-components.test.tsx
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/table-renderer-components.tsx
When scrolling horizontally in the ag-grid table the SearchFilterRenderer components are unmounted when out of view and then created again when scrolled back into view. This patch adds the filterModel as a prop to the SearchFilterRenderer in order to set a default value when it is created again.
Fixes #841
Signed-off-by: Ankush-Tyagi <ankush.tyagi@ericsson.com>
> Events Table search filter persists when scrolling horizontally

- packages/react-components/src/components/utils/filter-tree/__tests__/__snapshots__/entry-tree.test.tsx.snap
- packages/react-components/src/components/utils/filter-tree/__tests__/__snapshots__/table-row.test.tsx.snap
- packages/react-components/src/components/utils/filter-tree/__tests__/table-row.test.tsx
- packages/react-components/src/components/utils/filter-tree/table-cell.tsx
- packages/react-components/src/components/utils/filter-tree/table-row.tsx
There was a regression introduced by commits 05086c9 and 5396d83.
Fixes #774
> Fix selecting of timegraph row when tree row is selected

- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/utils/filter-tree/__tests__/__snapshots__/entry-tree.test.tsx.snap
- packages/react-components/src/components/utils/filter-tree/__tests__/__snapshots__/table-row.test.tsx.snap
- packages/react-components/src/components/utils/filter-tree/table-cell.tsx
- packages/react-components/src/components/utils/filter-tree/table-row.tsx
- packages/react-components/style/output-components-style.css
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-keyboard-shortcuts/time-graph-navigation-shortcuts-table.tsx
- yarn.lock
Navigation of markers using new cursor class 
Implements functionality to navigate through markers using "," & ".".
Includes new "TimeGraphMarkersChartCursors" layer and uses it with the
chart layer in the Markers Container.
Depends on: eclipse-cdt-cloud/timeline-chart#239
Signed-Off-By: Will Yang <william.yang@ericsson.com>
> Sync Trace-Extension for Markers-Navigation Update

- packages/react-components/src/components/timegraph-output-component.tsx
Changes made:
- Remove the properties from the tooltip object that have null values
This will provide the ability to remove keys from item properties by passing in null values.
Signed-off-by: Neel Gondalia ngondalia@blackberry.com
> Add null check to item properties

- examples/browser/webpack.config.js
- examples/electron/webpack.config.js
- packages/react-components/package.json
- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/utils/filter-tree/__tests__/__snapshots__/entry-tree.test.tsx.snap
- packages/react-components/src/components/utils/filter-tree/__tests__/__snapshots__/table-row.test.tsx.snap
- packages/react-components/src/components/utils/filter-tree/__tests__/table-row.test.tsx
- packages/react-components/src/components/utils/filter-tree/column-header.tsx
- packages/react-components/src/components/utils/filter-tree/entry-tree.tsx
- packages/react-components/src/components/utils/filter-tree/table-body.tsx
- packages/react-components/src/components/utils/filter-tree/table-cell.tsx
- packages/react-components/src/components/utils/filter-tree/table-row.tsx
- packages/react-components/src/components/utils/filter-tree/table.tsx
- packages/react-components/src/components/utils/filter-tree/tree.tsx
- packages/react-components/style/react-contextify.css
- yarn.lock
Columns of data type TIME_RANGE provide time ranges in the trace that can be selected and navigated to.
If data provider provides columns of TIME_RANGE then it creates a context-sensitive menu item to select that time range in the trace viewer.
Trace Compass patches to test:
- https://git.eclipse.org/r/c/tracecompass/org.eclipse.tracecompass/+/199993/3
- https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/199989/2
> Added support for time range columns in datatree-output-component

- packages/react-components/src/trace-explorer/trace-explorer-placeholder-widget.tsx
- packages/react-components/style/trace-explorer.css
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/theia-trace-explorer-placeholder-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
- Move the placeholder widget to the react-components npm package
- This would allow it to be used by both theia and vscode extension
> Created a widget for placeholder view in react-components

- README.md
As 17 is now the required java version to run trace-server.
Fixes #964.
> README: Replace Java v11 with 17 for trace-server

- yarn.lock
This includes performance improvement for state labels: https://github.com/eclipse-cdt-cloud/timeline-chart/pull/242
Bernd Hufmann <bernd.hufmann@ericsson.com>
> Upgrade to timeline-chart 0.3.0-next.20230419183309.9e0527f.0

- packages/base/src/utils/convert-color-string-to-hex.ts
Trims the whitespace off of the input string.  This fixes an issue that is occurring in the CodeOSS migration: https://github.com/eclipse-cdt-cloud/vscode-trace-extension/issues/116.
> Color String Whitespace hotfix

- packages/react-components/src/components/trace-context-component.tsx
- yarn.lock
The [performance improvement patch for the timeline chart](https://github.com/eclipse-cdt-cloud/timeline-chart/pull/246) changes the parameters provided to handlers of the onViewRangeChanged event on the unit controller. This commit updates the Theia Trace Extension to ensure that it works with the performance improvement patch.
This PR is to be merged after the performance improvement patch.
> Update parameter for onViewRangeChanged handler

- packages/react-components/style/output-components-style.css
- packages/react-components/style/react-contextify.css
- theia-extensions/viewer-prototype/style/trace-viewer.css
Previously, the --theia-menu-foreground CSS variable was replaced by  the variable --trace-viewer-foreground in an attempt to abstract the CSS definition. This is incorrect and the variable should have been mapped to --trace-viewer-menu-foreground instead. This commit corrects this error (where --theia-menu-foreground was previously --theia-menu-foreground).
Relates to #977.
> Rename --trace-viewer-foreground where applicable

- packages/react-components/style/trace-explorer.css
- theia-extensions/viewer-prototype/style/trace-viewer.css
The CSS variable --trace-extension-list-line-height is used in both the vscode and theia trace extension. This commit maps this CSS variable to --trace-viewer-trace-extension-list-line-height so each extension can declare its own style.
> Make --trace-extension-list-line-height a mappable CSS variable

- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/drop-down-component.tsx
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/style/output-components-style.css
The toggle columns menu item in the title bar menu was removed due to the refactor done in commit 35df458. This commit uses the addOption method that was introduced in commit 35df458 to bring back the toggle columns options.
Fixes #981.
> Fix toggle columns missing in title bar menu

- packages/react-components/src/components/drop-down-component.tsx
This commit makes checkboxes of the toggle columns menu readonly to resolve the error warning in the developer console. Since the on click handler is registered to the list item, there is no need to register an on change handler to the checkbox.
This commit also adds a key to each list item in the title bar menu drop down since it also triggers an error in the console.
Fix errors triggered by #985.
> Resolve warning errors with the toggle columns menu

- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
When triggering an open command, a trace server will be started if necessary. With this PR, upon successful start of trace server, the status indication and the opened trace view will be refreshed.
> Refresh open traces view on start during open

- package.json
- packages/react-components/src/components/data-providers/tsp-data-provider.ts
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/style/output-components-style.css
- yarn.lock
- Added a dialog-box to timegraph-output-component to search for events
- The view updates its contents as the user enters the string
- The filter is applied and unsuccessful time events are dimmed
This patch depends on:
- https://git.eclipse.org/r/c/tracecompass.incubator/org.eclipse.tracecompass.incubator/+/200991
- https://github.com/eclipse-cdt-cloud/timeline-chart/pull/243
[Screen Recording 2022-11-23 at 11.45.00 AM.webm](https://user-images.githubusercontent.com/92893187/203631862-460e6275-9397-4959-a152-7c8120d40979.webm)
The time event filtering uses its own domain-specific language (DSL) . Various logical operators are suppported:
- && performs a logical AND operation between two filter expressions. Example: ioctl && 5755
- || performs a logical OR operation between two filter …
> Search Time Events in Time Graph Views

- packages/react-components/src/components/__tests__/__snapshots__/table-renderer-components.test.tsx.snap
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/table-renderer-components.tsx
Added a check to see if any row elements match search. The color of search text updates to red if no results, and is unassigned (reverts to theme) if there are none.
This makes it more clear that a search does not have any results.
Signed-off-by: Dylan leclair dleclair@blackberry.com
> Added indicator for empty column search

- .github/workflows/publish-latest.yml
- .github/workflows/publish-next.yml
- .gitignore
- CONTRIBUTING.md
- package.json
Add a `publish-latest` GitHub workflow similar to the existing `publish-next`.
- Make the former trigger on merging a commit that bumps the package versions depending on the chosen yarn script command.
- Hence, make the latter trigger only on the other kinds of commits.
- Align `publish-next` (with `publish-latest`) also so its previous trivial nits don't show as differences, upon comparing the two files for review purposes or so.
Beside the usual goal of publishing onto the npm Registry, use the `github-tag-action` in `publish-latest`, to push the corresponding tag after that publishing.
- Make the hereby generated commit (message) automatically convey how to name that bumped tag.
- For that purpose, `github-tag-action` uses a message token such as `#major`, `#minor` or `#patch`.
- Here, …
> releng: Define publishing latest semantic versions

- .git-blame-ignore-revs
Prettier was introduced with PR #973, but SHA in .git-blame-ignore-revs was not updated after it was merged.
> Fix SHA in git-blame-ignore-revs to commit of prettier format change

- doc/performance/0002-http-vs-rcp-client-performance-analysis.md
This commit adds a study on the impact of the JSON-RPC patch on the Theia Front End - Back End - Trace Server communication speed.
Relates to #990.
> Measure performance of TSPClient before and after JSON-RPC

- packages/base/src/signals/signal-manager.ts
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/utils/timegraph-container-component.tsx
Introduced a new signal to indicate that the data on the server has been updated and therefore the components should refetch the data and rerender the components. This PR handles the signal in table-output-component and timegraph-output-component. We have a use case where data is modified on the server, and we want the components to rerender with the new data. Currently, the user would have to close the active trace panel and reopen it to see the changes.
> Added output data changed signal

- packages/react-components/src/components/abstract-xy-output-component.tsx
- packages/react-components/src/components/utils/xy-output-component-utils.tsx
- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/src/components/xy-output-overview-component.tsx
Some traceviewer-base imports still use the src directory instead of lib. This commit fixes this.
> Use 'traceviewer-base/lib' instead of 'traceviewer-base/src'

- doc/adr/0002/graphql-server-prototype/index.js
- package.json
- packages/base/src/experiment-manager.ts
- packages/base/src/lazy-tsp-client.ts
- packages/base/src/trace-manager.ts
- packages/base/src/tsp-client-provider.ts
- packages/react-components/src/components/__tests__/table-renderer-components.test.tsx
- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/data-providers/style-provider.ts
- packages/react-components/src/components/data-providers/tsp-data-provider.ts
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/components/trace-overview-selection-dialog-component.tsx
- theia-extensions/viewer-prototype/src/browser/preferences-frontend-contribution.ts
- theia-extensions/viewer-prototype/src/browser/theia-rpc-tsp-proxy.ts
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-server-connection-status-client-impl.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
- theia-extensions/viewer-prototype/src/browser/tsp-client-provider-impl.ts
- theia-extensions/viewer-prototype/src/common/trace-server-config.ts
- theia-extensions/viewer-prototype/src/common/trace-server-connection-status.ts
- theia-extensions/viewer-prototype/src/common/trace-server-url-provider.ts
- theia-extensions/viewer-prototype/src/node/trace-server-connection-status-backend-impl.ts
- theia-extensions/viewer-prototype/src/node/trace-server-url-provider-impl.ts
- theia-extensions/viewer-prototype/src/node/viewer-prototype-backend-module.ts
- yarn.lock
**Update to newest tsp-typescript-client next version**
To consume the new types introduced with https://github.com/eclipse-cdt-cloud/tsp-typescript-client/pull/83.
Invoke the yarn clean script before running the prepare script.
Make sure all imports are from `lib` instead of `src`.
**Update types of base package and react-components**
Use the newly introduced types of tsp-typescript-client.
The type of TspClient becomes ITspClient.
The constructor for the base implementation becomes HttpTspClient.
**Refactor server communication to JSON-RPC**
TspClient Proxy:
Provide an implementation of the ITspClient called `TheiaRpcTspProxy`.
The implementation forwards all calls to a JSON RPC proxy called `TheiaClientProxy`.
Responses are then mapped to a `TspClientResponse`.
On the backend the …
> Refactor server communication to JSON-RPC

- examples/browser/package.json
- examples/electron/electron-builder.yml
- examples/electron/package.json
- lerna.json
- package.json
- yarn.lock
Updated lerna from v4.x to 7.x, getting rid of several big security vulnerabilities, that were present in the older version. Also updated their repo's root README to do small adjustments, related to the changes. I used the README to test too, replicating the contained commands.
More details:
root package.json and electron/browser package.json:
Cleaned-up the "scripts" section.
Some uses of lerna in there were not working any more, so they were replaced with a non-lerna alternative. Since I was already in there, I took the opportunity to refactor the "scripts" section. I attempted to keep the "public API" the same - i.e. so the the commands that are documented in the README and used elsewhere in the repo should still work the same.
For instance:
- Added convenience shortcuts to call …
> [lerna] upgrade to recent version, refactoring of package.json "scripts" entries

- package.json
- packages/react-components/package.json
MaterialUI was installed in the top-level node_modules.  It's moved to the correct one in /packages/react-components/ where it's used.
This may fix eclipse-cdt-cloud/vscode-trace-extension/issues/175 according to this [stackoverflow thread](https://stackoverflow.com/questions/72413194/uncaught-typeerror-cannot-read-properties-of-null-reading-usecontext).
> Move MaterialUI to proper package.json

- doc/adr/0011-tsp-analysis-api.md
ADR: 0011-tsp-analysis-api.md
The list of ConfigurationParameterDescriptor replaces the list of QueryParameterKeys. Using just the keys would be too restrictive and ambiguous for clients to implement.
> ADR: Update ConfigurationSourceType to provide parameter descriptors

- packages/react-components/src/components/abstract-xy-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
Add 's' or 'ns' unit to timestamps and durations in tooltips for timegraph output component and xy output component.
Fixes issue #1027
> Add unit to timestamps and durations in tooltips

- theia-extensions/viewer-prototype/src/browser/theia-rpc-tsp-proxy.ts
- yarn.lock
This includes the new configuration end-points. Add implementations of the new methods to theia-rpc-tsp-proxy.ts.
See also:
- https://github.com/eclipse-cdt-cloud/tsp-typescript-client/pull/87
- https://github.com/eclipse-cdt-cloud/trace-server-protocol/pull/92
- https://github.com/eclipse-cdt-cloud/trace-server-protocol/pull/93
> Upgrade tsp-typescript-client to 0.4.0-next.20231003144311.a5128df.0

- yarn.lock
Without that change yarn.lock will updated and the publish operation fails.
> Fix yarn.log for json-bigint dependency

- examples/docker/Dockerfile
- examples/docker/README.md
- examples/docker/docker-entrypoint.sh
- examples/docker/example-package.json
- examples/docker/startup.sh
Before this commit the docker example was not properly building. The issue was introduced when moving from Theia 1.3x to 1.4x, where an extra step in the build process was introduced (i.e. running "yarn" was not enough, an extra "theia" command was needed).
After this commit:
- the docker example is building again
- the docker image generated is stable and reproducible, not based on "next"
- the docker image is much smaller thanks to a multistage build
> docker: fix and improve docker example

- .github/workflows/build.yml
In a recent CI run, I noticed this [error](https://github.com/eclipse-cdt-cloud/theia-trace-extension/actions/runs/7223312899/job/19682105853):
"Downloading ripgrep failed: Error: Request failed: 403"
This can randomly happen on CI machines, because GitHub has limits when anonymously accessing its API, which we do when downloading `ripgrep`. There's an easy fix: use an auto-generated GitHub token when building the Theia app.
Also tidied-up the workflow file a little, to make it easier to read.
> [ci] Use GitHub token to avoid ripgrep download issue

- README.md
@MatthewKhouzam recently added a video that shows how to try the trace viewer via the CDT cloud live demo. I thought it could be relevant to add this information to the repo readme as well.
Phrasing and content edits welcome!
> README: Add cdt cloud demo link

- yarn.lock
Check-in updated yarn.lock, which I think I missed in the last PR. ATM, this prevents the publish workflow from working: 
https://github.com/eclipse-cdt-cloud/theia-trace-extension/actions/runs/7702565918/job/20991122775#step:5:13
> Check-in updated yarn.lock

- .gitignore
- examples/docker/example-package.json
Follow-up, after updating to Theia 1.45.1. Update the specific version of the trace extension that's used in the docker image example.
> [Theia v1.45.1] update trace extension used in docker image

- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-server-status-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-server-connection-status-client-impl.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
- theia-extensions/viewer-prototype/src/common/trace-server-connection-status.ts
This is to improve the tracking of TraceServer status state in the application.  This will support the implementation of the remote use case in the vscode-trace-extension.
This change consists of four commits:
1) **Rename subscription events in Connection client**
'addConnectionStatusListener' changed to 'activate'
'removeConnectionStatusListener' changed to 'deactivate'
This is more accurate.
2) **Add Server Status Change Listeners**
Adds methods to add and remove functions that are executed when the
server status is updated.
3) **Remove Direct DOM Manipulation from ServerStatusWidget**
Removes direct DOM manipulation from TraceExplorerServerStatusWidget.
Refactors it to use the server status change event listeners and change
what is rendered through Theia ReactWidget's component …
> Refactor Connection Status Logic

- examples/docker/example-package.json
- package.json
- yarn.lock
This dependency comes from `@theia/core` and currently has a high level vulnerability. Until Theia steps to a safe version, we can use a local "resolution" so that our test applications will pull a safe version.
Note: Other Theia applications, that use the theia trace extension, should have their own resolution, if needed - the one in this repo will not work for them.
> [security] Pin msgpackr dependency to a safe version

- packages/base/src/signals/context-menu-contributed-signal-payload.tsx
- packages/base/src/signals/context-menu-item-clicked-signal-payload.tsx
- packages/base/src/signals/row-selections-changed-signal-payload.tsx
- packages/base/src/signals/signal-manager.ts
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/utils/filter-tree/entry-tree.tsx
- packages/react-components/src/components/utils/filter-tree/table-body.tsx
- packages/react-components/src/components/utils/filter-tree/table-row.tsx
- packages/react-components/src/components/utils/filter-tree/table.tsx
- packages/react-components/src/components/utils/filter-tree/tree.tsx
- packages/react-components/src/trace-explorer/trace-explorer-sub-widgets/time-graph-navigation-shortcuts-table.tsx
- packages/react-components/style/output-components-style.css
- packages/react-components/style/react-contextify.css
Changes made:
- Support for adding context menu via signals
- Support for making multiple selections in data tree of timegraph component
- Added Signals to notify context menu selection and multi row selections
This change will allow for a context menu to be added to the timegraph component based on the outputDescriptor id via a signal. The component also adds the ability to select multiple rows. The multi selections can be passed with the item clicked signal payload as well as through a rowSelectionsChanged signal. The end goal is to provide the timegraph views with the ability to make multi-row selections and perform some actions with the selections.
Signed-off-by: Neel Gondalia ngondalia@blackberry.com
> Add support for multi row select and context menu in Timegraph Component

- packages/react-components/src/trace-explorer/trace-explorer-placeholder-widget.tsx
- packages/react-components/style/trace-explorer.css
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/theia-trace-explorer-placeholder-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-commands.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-commands.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx
This commit adds another button for opening trace files through a dialog. Futhermore, the theia-trace-explorer-placeholder-widget can be configured to render either one or both buttons (Open Trace folder, Open Trace File).
Fixes #1053
Signed-off-by: Neel Gondalia <ngondalia@blackberry.com>
> Support opening trace files through a dialog

- .gitignore
- README.md
- examples/browser/package.json
- examples/electron/package.json
This PR reverts the recent change in release/publish documentation. It's no longer necessary to manually handle the update of version of "theia-traceviewer" for the browser and electron examples, with the change in "git ignore" strategy, that's also included in this PR (separate commit). 
Until now, the example applications were ignored by default, with a few files having exceptions. This had a non-obvious side-affect when using `lerna version`, which would then ignores these folders even if they are part of the lerna workspace. This resulted in our root package.json "version:<*>" "scripts" entries, not updating the version of the "theia-traceviewer" dependency in the examples package.json, which we then had to do manually. 
See below for a test run of "yarn version:major" that shows …
> [examples] "Git ignore" strategy change: blanket ignore -> granular ignore

- packages/base/package.json
- packages/react-components/package.json
- yarn.lock
Now that we can easily publish solid (latest) revisions of these dependencies, let's switch to requesting a "solid" version range, for them, instead of using "next". From now-on, these dependencies should be managed like any other production dependencies.
~~Note: waiting for a release of `timeline-chart` that contains the size improvements and will then update this PR to pick-up that version.~~
Done - PR updated
> [timeline-chart][tsp-typescript-client] Switch to solid versions

- RELEASE
- examples/browser/package.json
- examples/electron/package.json
- lerna.json
- packages/base/package.json
- packages/react-components/package.json
- playwright-tests/package.json
- theia-extensions/viewer-prototype/package.json
Trigger a patch release (V0.2.1) so that the npm packages in this repo, that we recently updated to use solid revisions of our own-produced dependencies (published as "latest" to npm vs "next") are used. 
Note: the playwright folder's package.json got reformatted by "lerna version"- it's a one-time thing - now that it's done in this commit, next release only the version number should be updated.
> Release v0.2.1 (Patch)

- examples/docker/Dockerfile
- examples/docker/webpack.config.js
Add webpack.config.js to example docker image. 
Some views like statistics view have features to right-click on the entries and select time ranges, but this feature requires some Node.js-specific features like "process", which is missing for the docker example.
Fixes #1066
Signed-off-by: Siwei Zhang <siwei.zhang@ericsson.com>
> Add webpack.config.js to docker example

- packages/base/src/signals/item-properties-signal-payload.tsx
- packages/base/src/signals/signal-manager.ts
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/utils/filter-tree/table-body.tsx
- packages/react-components/src/components/utils/filter-tree/table-cell.tsx
- packages/react-components/src/components/utils/filter-tree/table-header.tsx
- packages/react-components/src/components/utils/filter-tree/table-row.tsx
- packages/react-components/src/components/utils/filter-tree/table.tsx
- packages/react-components/src/components/utils/filter-tree/tree-node.tsx
- packages/react-components/src/components/utils/filter-tree/tree.tsx
- packages/react-components/src/trace-explorer/trace-explorer-properties-widget.tsx
- packages/react-components/style/output-components-style.css
- packages/react-components/style/trace-explorer.css
The current implentation of the item properties view shows properties as plaintext with no styling. This looks ok but can be significantly improved by showing the properties in a table.
This commit makes the following changes:
- Reuses filter tree component for item properties view.
- Added option to hide filler columns/cells
- Ability to render a table cell value as an element
- Added tooltips for item properties
Signed-off-by: Neel Gondalia <ngondalia@blackberry.com>
> Refactor Item Properties View to use table components

- theia-extensions/viewer-prototype/package.json
- yarn.lock
This was accidentally removed during streamling of the example app. See commit 4c58c03
> Add back @theia/messages dependency to show toast messages

- examples/browser/package.json
- examples/electron/package.json
- package.json
- theia-extensions/viewer-prototype/package.json
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
- yarn.lock
Update to Theia community release version 1.49.1
> update to latest Theia community release: v1.49.1

- packages/react-components/src/components/trace-context-component.tsx
This fixes a bug.  When a user is typing in a search box or search box, some keyboard shortcuts were triggering.
Adds a check to 'onKeyDown' event handler that checks if the user is focused on an input or textinput field.  If true, does not proceed with executing keyboard shortcuts.
Signed-off-by: William Yang <william.yang@ericsson.com>
> Don't trigger keyboard shortcuts when typing

- packages/base/package.json
- packages/react-components/package.json
- yarn.lock
We have just published new versions of these key dependencies, with fresh "yarn upgrade" performed on them.
> Adopt latest timeline-chart and tsp-typescript-client

- packages/react-components/src/components/__tests__/__snapshots__/table-renderer-components.test.tsx.snap
- packages/react-components/src/components/__tests__/table-renderer-components.test.tsx
Fixes #1100
Had to mock some ag-grid objects that were used in the newly re-enabled tests.
It turns-out that many of these objects were not really used during our tests
(e.g. api: GridApi, column: Column). So for these, it was enough to mock
them using an empty JS object and use keyword "as" to present them as the real
thing. e.g.:
```JS
<SearchFilterRenderer
api={{} as GridApi}
column={{} as Column<any>}
>
```
To run the re-enabled tests against the original jest snapshots, you can checkout the snapshot file's version prior to the ag-grid upgrade:
```bash
$ pwd
<...>/theia-trace-extension
$ git log --oneline 
[...newer commits]
b911f00 Bump ag-grid-community from 28.2.1 to 32.0.1  // **6-deep vs this PR**
167c526 Update 0011-tsp-analysis-api for custom analysis // **7-deep vs this PR** …
```
> Re-enable all React table-renderer-components tests

- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/style/output-components-style.css
Enables filtering in gant-chart views.  Implements UI and functionality.
This change is dependent on changes in the Timeline-Chart repo for the filtering of gap-states.
See: https://github.com/eclipse-cdt-cloud/timeline-chart/pull/285
Signed-off-by: William Yang <william.yang@ericsson.com>
> Filtering in Timeline-Chart components

- packages/react-components/src/components/abstract-xy-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/style/output-components-style.css
Initialize the unit controller view range with either the trace full
range, or the persisted state view range if it is set. When the
experiment hasn't been indexed yet, the initial view range may be empty.
When a new output is opened while the trace is indexing, and the view
range has never been set yet, initialize the view range to the current
partial trace full range. This view range will remain during and after
indexing unless the user changes the view range manually or presses the
Reset button.
When indexing completes, if the view range has never been set yet,
initialize the view range to the final trace full range.
In TimegraphOutputComponent, render the timegraph content and use the
analysis-running-overflow overlay while the analysis is running.
Let the analysis-running-overflow …
> Initialize view range and render time charts during trace indexing

- packages/react-components/src/components/timegraph-output-component.tsx
When a filter is applied, updateChart() should not be called without the
filter expression map.
Replace method updateSearchFilters(), which computes the filter
expression map and calls updateChart with the map if it applies, with
method filterExpressionsMap() which only computes the map. This method
is now always called to compute the parameter to be passed in
updateChart().
Remove the updateSearchFilters callback when adding or removing a filter
as the state change will handle it already.
Method _debouncedUpdateSearch() is removed, as _debouncedUpdateChart()
can always be used instead.
> Fix updateChart() missing filter expressions map

- configs/license-check-exclusions.json
- examples/browser/package.json
- examples/electron/electron-builder.yml
- examples/electron/package.json
- package.json
- packages/react-components/src/components/__tests__/__snapshots__/table-renderer-components.test.tsx.snap
- theia-extensions/viewer-prototype/package.json
- yarn.lock
This PR updates `@theia` extension `theia-traceviewer` so it uses the latest Theia community release (v1.52.0). Same for the browser and electron example applications in this repo. 
TODO:
Note: there is a separate [PR](https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1119) (#1119) to deal with the "open-with" no longer working with folders, since Theia 1.50.0 IIRC. We will probably want to merge that one too, before publishing a new version of `theia-traceviewer`. suitable for Theia 1.52.0 (latest community release)
> Update to latest Theia community release: v1.52.0

- packages/react-components/package.json
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/utils/filter-tree/entry-tree.tsx
- packages/react-components/src/components/utils/filter-tree/table.tsx
- packages/react-components/src/components/utils/filter-tree/tree.tsx
- packages/react-components/src/components/utils/filter-tree/utils.tsx
- yarn.lock
Hide rows that have no non-null state in their model, when a filter is applied. Gaps between states in the row model should be make rows visible when strategy is SAMPLED, but not when it is DEEP.
Keep an up-to-date list of empty nodes after fetching row models from the server.
Add emptyNodes and hideEmptyNodes to the properties of EntryTree, Tree and Table. Filter the empty nodes when rendering the Table.
Remove the updateSearchFilters callback when adding or removing a filter as the state change will handle it already.
Removed unused dataRows in TimegraphOuputState
> Hide empty rows when filter is applied

- .github/workflows/ci-cd.yml
Add libsecret-1-dev to ubuntu image to ci-cd workflow
Latest is now Ubuntu 24.04 and the runner doesn't include this library.
> Add libsecret-1-dev to ubuntu image of ci-cd workflow

- doc/adr/0011-tsp-analysis-api.md
See https://github.com/eclipse-cdt-cloud/trace-server-protocol/pull/103
> Update adr json schema

- packages/react-components/package.json
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/utils/filter-tree/table-body.tsx
- packages/react-components/src/components/utils/filter-tree/table.tsx
- packages/react-components/src/components/utils/filter-tree/tree.tsx
- packages/react-components/src/components/utils/filter-tree/utils.tsx
- yarn.lock
Update the filtering of empty nodes to include visible nodes even if any of their parent is filtered-out. Recursively replace filtered-out nodes by their visible children, if any, but only if the filtered-out parent node is not collapsed.
In TimeGraphOutputComponent update the arrows layer after empty nodes have been determined, and filter out empty nodes from the rowIds passed to the arrows layer.
Fixes #1132
> Fix time graph filtering and collapsing

- packages/react-components/style/output-components-style.css
**Before in vscode-trace-extension**:
**After: in vscode-trace-extension**
> Update filter-chip style so that it can be styled in vscode

- packages/react-components/src/components/utils/filter-tree/table-cell.tsx
- packages/react-components/src/components/utils/filter-tree/tree-node.tsx
- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
- packages/react-components/style/output-components-style.css
- Use FilterTree
- Add tooltips to TreeNode and TableCell
- Enable sorting and filter
- Description of view is part of the tooltip instead of being printed below view name
fixes #1113
> Use filter table tree for Available Views view implementation

- packages/react-components/src/components/utils/filter-tree/filter.tsx
- packages/react-components/style/output-components-style.css
Use box-sizing: border-box setting so that the provided width includes the filter text box padding and border.
Use the reference element's right position as provided width so that it can include the reference element's left margin.
> Fix filter tree filter text box width

- packages/base/package.json
- packages/react-components/package.json
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
- theia-extensions/viewer-prototype/src/browser/theia-rpc-tsp-proxy.ts
- yarn.lock
- Adopt tsp-typescript-client v0.5.0
- Use ProviderType enum instead of string for outputs
- Update API for global configuration
- Add new methods of ITspClient in TheiaRpcTspProxy
Requires https://github.com/eclipse-cdt-cloud/tsp-typescript-client/pull/119 (part of tsp-typescript-client v0.5.0)
> Follow recent tsp-typescript-client API additions for configurations

- examples/docker/example-package.json
- packages/base/package.json
- packages/react-components/package.json
- yarn.lock
- Use resolution to pin inversify to v6.0.3 to avoid docker build errors
The docker example doesn't have yarn.lock file and hence the builds starts fresh. The new inversify version v6.1.x cause a build error.
- Adopt tsp-typescript-client version 0.5.1
> Adopt tsp-typescript-client version 0.5.1 and pin inversify to 6.0.3

- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
With this it's guaranteed that the styles are loaded when using this react component outside this repository (e.g. in vscode-trace-extension)
> Import style in trace-explorer-views-widget.tsx

- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/style/output-components-style.css
No header is drawn with the commit.
Fixes #1149
> Show column in TimegraphOutputComponent if back-end provides them

- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/utils/filter-tree/entry-tree.tsx
- packages/react-components/style/output-components-style.css
v0.4.2 introduced vertical gridlines for the trees of timegraph views (see #1152) . However, 2 vertical lines were drawn so that they appeared thicker. This commit fixes that.
Besides, the vertical line on the right of the last column are not drawn anymore. For that, the hideFiller flag needed to be added to the EntryTree props so that that flag can be set to true, propagated and hence the filler column can be hidden.
Here how it looks like with this PR:
> Improve display of vertical tree gridlines in timegraph views

- theia-extensions/viewer-prototype/src/node/backend-file-service-impl.ts
The trace detection algorithm checks recursively for CTF traces. If no CTF trace are found under the root directory, then use the root directory as trace directory. The trace server back-end will validate if this path points to a valid trace or not.
With this it's now possible to open traces that are directories other than CTF.
Note that only a single trace can be opened in the experiment and not set of traces, which is currently only supported with CTF traces.
Examples trace type: uftrace
> Support of directory traces other than CTF

- packages/base/src/experiment-manager.ts
- packages/base/src/signals/signal-manager.ts
- packages/base/src/trace-manager.ts
- packages/react-components/src/components/abstract-output-component.tsx
- packages/react-components/src/components/datatree-output-component.tsx
- packages/react-components/src/components/table-output-component.tsx
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/trace-context-component.tsx
- packages/react-components/src/components/trace-overview-selection-dialog-component.tsx
- packages/react-components/src/components/utils/available-views-component.tsx
- packages/react-components/src/components/xy-output-component.tsx
- packages/react-components/src/trace-explorer/trace-explorer-opened-traces-widget.tsx
- packages/react-components/src/trace-explorer/trace-explorer-properties-widget.tsx
- packages/react-components/src/trace-explorer/trace-explorer-time-range-data-widget.tsx
- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/theia-trace-explorer-opened-traces-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
> ⚠️ **IMPORTANT: Dependency Warning** ⚠️
> 
> This PR introduces type changes that will affect the `vscode-trace-extension` repository.
> **DO NOT MERGE** until maintainers have reviewed and approved the proposed changes.
> A corresponding PR will need to be created in `vscode-trace-extension` to handle these type updates.
>
> 👉 Maintainers: Please review and comment on the proposed type system before work begins on the extension repository.
This PR refactors the SignalManager to provide better TypeScript support and improved developer experience. The changes focus on making the event system more type-safe while reducing boilerplate code.
```typescript
// Before - No type inference on payload
signalManager.on('THEME_CHANGED', (theme) => {
console.log(theme.toUpperCase()); // TS doesn't …
```
> SignalManager: improve type safety and reduce boilerplate

- packages/react-components/src/components/table-renderer-components.tsx
Use global regex to get all matching strings not only the first match.
Handle different behavior of String.split() when regex contains capturing groups.
Fixes #1160
Try a regex with multiple not-equal matches, e.g. a|b.
Try a regex with captured matching groups, e.g. (a|b).
Try a regex with captured and uncaptured matches, e.g. a|(b)
N/A
> Fix table cell renderer highlighting of search term matches

- packages/react-components/src/components/utils/filter-tree/__tests__/__snapshots__/entry-tree.test.tsx.snap
- packages/react-components/src/components/utils/filter-tree/filter.tsx
- packages/react-components/src/trace-explorer/trace-explorer-opened-traces-widget.tsx
- packages/react-components/style/output-components-style.css
Add filter container to ReactOpenTracesWidget. Add filter string to the widget's state.
When filter is applied, hide rows that don't match the filter for neither the experiment name nor any of the experiment's traces' name. Rows are hidden by returning 0 as row height and rendering to undefined.
Rename CSS class 'input-filter-tree' to generic 'input-filter-text'.
Open a few traces and experiments with multiple traces. Type filter strings that match experiment names, trace names, both or none. Repeat with a selected experiment.
N/A
> Add filter to Opened Traces widget

- packages/react-components/src/trace-explorer/trace-explorer-opened-traces-widget.tsx
Modernizes method binding patterns in `OpenedTracesWidget` as part of #1173.
1. Run the existing test suite
2. Verify REFACTORED_COMPONENT functionality remains unchanged
3. Review code changes to confirm all delegation patterns and `.bind(this)` calls have been replaced with arrow functions
No technical debt introduced. This PR reduces existing technical debt by simplifying the codebase.
> OpenedTracesWidget: modernize method binding

- packages/react-components/src/trace-explorer/trace-explorer-opened-traces-widget.tsx
Import style in `trace-explorer-opened-traces-widget.tsx`. With this it's guaranteed that the styles are loaded when using this react component outside this repository (e.g. in `vscode-trace-extension`). This is consistent how other components import their styles (e.g. see commit 8e545aa).
No change when running in theia-trace-extension.
> Import style in trace-explorer-opened-traces-widget.tsx

- examples/browser/package.json
- examples/browser/webpack.config.js
- examples/electron/package.json
- examples/electron/scripts/theia-trace-main.js
- examples/electron/webpack.config.js
- package.json
- theia-extensions/viewer-prototype/package.json
- yarn.lock
Update to Theia community release v1.58.5. 
Also, this PR includes using the bundled Electron backend, which is a simple webpack config update. If we later notice issues with this, we can roll-back to use the non-bundled backend in the next community release, which will have the fix above. See commit message for more details about this and why it was necessary.
Note about the webpack config update: as suggested, I have deleted the webpack configs and run "theia build" to have them re-created. Then I re-added the small change we need for the time range context menu. The result is a webpack config that's more aligned with the one Theia generates, for both our example Theia apps.
Make sure the trace viewer still works as expected. Also, since the webpack config was updated, also confirm that …
> Update for Theia community release v1.58.5

- packages/react-components/src/components/utils/filter-tree/__tests__/__snapshots__/entry-tree.test.tsx.snap
- packages/react-components/src/components/utils/filter-tree/__tests__/__snapshots__/table-row.test.tsx.snap
- packages/react-components/src/components/utils/filter-tree/table-cell.tsx
- packages/react-components/src/components/utils/filter-tree/table-row.tsx
- packages/react-components/src/components/utils/filter-tree/tree-node.tsx
- packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
- packages/react-components/style/output-components-style.css
- theia-extensions/viewer-prototype/package.json
- theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/theia-trace-explorer-views-widget.tsx
- theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
- yarn.lock
This PR enhances the React components package to support trace output customization, providing the UI elements needed to trigger and manage customized outputs. These changes complement the JSON configuration editor implemented in the main repository.
- Added ability to customize trace outputs directly from the Available Views panel
- Implemented UI for adding custom analysis to existing outputs
- Added support for removing custom outputs
- Enhanced filter tree nodes to display interactive buttons
- Extended `TreeNode` interface to support enriched content rendering
- Modified `TableCell` to use enriched content when available
- Added button components for adding and removing outputs
- Implemented handlers for customization and deletion operations
- Added styling for custom buttons and UI …
> Add UI Components for Trace Output Customization

- examples/browser/package.json
- examples/electron/package.json
- package.json
- playwright-tests/package.json
- theia-extensions/viewer-prototype/package.json
- yarn.lock
Because of how Theia resolves its dependencies, Theia apps cannot successfully include more than one version of Theia extensions (e.g. @theia/core), even if they are compatible.
Since a new butfix Theia release happened after we updated the Theia extension in this repo to use Theia 1.61.0, we need to follow. This time I took the precaution of requesting a version range that will include potential future 1.61.x bugfix Theia releases, using "~". e.g.:
"@theia/core": "~1.61.1"
There's a small risk that a future Theia v1.61.x might break for
us, but OTOH if we do not do this, the theia-traceviewer extension
will not work with these anyway - so this seems like a worthy trade-off.
Confirm CI passes
> Update for Theia 1.61.1 and later (from 1.61.0)

- packages/react-components/package.json
- packages/react-components/src/components/timegraph-output-component.tsx
- packages/react-components/src/components/utils/time-axis-component.tsx
- packages/react-components/src/components/utils/time-navigator-component.tsx
- yarn.lock
There's a relatively low limit of WebGL contexts available for a Chrome-based browser tab (16). Each time a "TimeGraphContainer" is created, one such context is consumed. We use these contexts for a few things, not just time-line charts (where it makes most sense).
This commit takes advantage of the new option and declines that a WebGL context be used for containers we create, except for proper timeline chart views and marker containers. This means that we will now be able to create about 8 timeline-chart views per session (each uses 2 WebGL contexts), spread over however many experiments.
~~Note: Depends on the following timeline-chart PR, where the `forceCanvasRenderer` option is added in the `TimeGraphContainerOptions` interface:~~ …
> Use TimeGraphContainer forceCanvasRenderer option

- packages/react-components/src/components/timegraph-output-component.tsx
Wait for table header to be rendered before setting top margin.
Fixes #1207
Remove trace from trace viewer if it exists, to make sure analyses haven't run
Open a timegraph output with a slow analysis, or use breakpoint in analysis to simulate a delay
Wait for analysis to complete, or exit the breakpoint
Observe that timegraph has a top margin equal to tree header and rows are aligned with the tree
N/A
> Fix timegraph misalignment when analysis running

- packages/react-components/style/output-components-style.css
Set the height for timegraph td in .css stylesheet since the line-height for timegraph tr does not apply if there is no text.
Fixes #1208
Open kernel trace and Resources status view. Check that separator rows between CPUs have same height in tree and timegraph.
Consider supporting variable height rows. See issue #133.
> Fix timegraph misalignment when entry label is blank

- local-libs/traceviewer-libs/react-components/src/components/abstract-gantt-output-component.tsx
Check if style.parentKey field is available before using it. This is in preparation of an update in the tsp-typescript-client where the parentKey is marked as optional to match the TSP.
Modify TSP typescript client to make it optional and use it in development environment. The code should compile with this change. 
N/A
> Check if style.parentKey field is available before using it.
