eclipse-cdt-cloud/theia-trace-extension

yarn.lock

Update yarn.lock to latest versions

---

.vscode/launch.json

Add launch configurations for debugging the viewer-prototype

---

viewer-prototype/src/browser/style/trace-explorer.css
viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx

Highlight selected trace in trace explorer

---

yarn.lock

Upgrade versions in yarn.lock which includes the latest Theia version

---

viewer-prototype/src/browser/trace-viewer/components/abstract-tree-output-component.tsx
viewer-prototype/src/browser/trace-viewer/components/timegraph-output-component.tsx
viewer-prototype/src/browser/trace-viewer/components/xy-output-component.tsx

The tree and the chart are synchronized when scrolling and wheeling.
The tree's rows are equalized with the chart's rows.

Timegraph: Tree and chart synchronization

---

.vscode/launch.json
viewer-prototype/src/browser/style/status-bar.css
viewer-prototype/src/browser/style/trace-explorer.css
viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
viewer-prototype/src/browser/trace-server-status.ts
viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts

Add warning when trace server is offline

---

yarn.lock

Update yarn.lock to pick-up recent timeline-chart updates incl. pixi 5.x

---

viewer-prototype/src/browser/trace-viewer/components/data-providers/tsp-data-provider.ts
viewer-prototype/src/browser/trace-viewer/components/timegraph-output-component.tsx
viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/entry-tree.tsx
viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/tree-node.tsx
viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/utils.tsx
yarn.lock

The chart is updated when collapsing or expanding entries in the tree.
Also, fixed the entries alignment with the chart's rows.

Timegraph chart: Support for the tree view on the left of the chart

---

viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/utils.tsx

Handle missing labels in entry gracefully

---

viewer-prototype/src/browser/trace-viewer/components/data-providers/tsp-data-provider.ts

Fixes #117
Signed-off-by: soukaina <soukaina.moussaoui@polymtl.ca>

Timegraph: Fixed undefined timeGraphEntries in tsp-data-provider

---

viewer-prototype/src/browser/trace-viewer/components/utils/timegraph-container-component.tsx
yarn.lock

This pull request is dependent on https://github.com/theia-ide/timeline-chart/pull/45
fixes #135 

Set Focus on Canvas to handle keypress events

---

viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/utils.tsx

#129: Keep order of tree entries returned by the data provider

---

viewer-prototype/src/browser/trace-viewer/components/timegraph-output-component.tsx

Rows do not render because of a runtime error

---

viewer-prototype/src/browser/trace-viewer/components/timegraph-output-component.tsx
yarn.lock

Remove state selection
This logic is already handled in timeline-chart. And validating states with id is incorrect. Hence removed it from this file.
This PR is dependent on https://github.com/theia-ide/timeline-chart/pull/49

TimeGraph Rows and States deselects when zooming in/out

---

viewer-prototype/src/browser/trace-viewer/components/data-providers/tsp-data-provider.ts
yarn.lock

- Added next and prev possible state fields to each row in tsp-data-provider.ts and stored the values from first and last null states.
- Start time of first null state gives the timestamp of previous possible state.
- End time of last null state gives the timestamp of next possible state.
fixes #166 
This PR is dependent on https://github.com/theia-ide/timeline-chart/pull/58

Improve State Navigation using Left/Right Arrow Buttons

---

viewer-prototype/src/browser/trace-viewer/components/timegraph-output-component.tsx

Fix backup styles lookup for data providers that don't provide styles

---

viewer-prototype/src/browser/trace-viewer/components/data-providers/tsp-data-provider.ts

Added default style to GAP states 

---

.vscode/launch.json
package.json
viewer-prototype/.eslintrc.js
viewer-prototype/jest.config.json
viewer-prototype/jestSetup.ts
viewer-prototype/package.json
viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/__tests__/__snapshots__/entry-tree.test.tsx.snap
viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/__tests__/__snapshots__/table-row.test.tsx.snap
viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/__tests__/entry-tree.test.tsx
viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/__tests__/table-row.test.tsx
viewer-prototype/src/browser/trace-viewer/components/utils/filtrer-tree/__tests__/utils.test.tsx
viewer-prototype/tsconfig.json
yarn.lock

Add tests for the filter tree

---

viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

Sync Experiments in Explorer and Viewer

---

viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx

Disable Share Experiment feature (temporary)

---

packages/base/src/experiment-manager.ts

Use the same code for the first and subsequent attempts.

Simplify openExperiment conflict handling

---

packages/base/src/trace-manager.ts

Use the same code for the first and subsequent attempts.
Set the name from traceURI if traceName is not specified.
Fix undefined base name in retry attempts.

Fix and simplify openTrace conflict handling

---

viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts

Add Open Trace option to Menu & Trace Explorer

---

viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

In case a user selects a directory with large directory structure,
allow user to cancel the open procedure.
Fixes #195

Provide progress monitor for opening an experiment with cancel option

---

packages/react-components/src/components/data-providers/tsp-data-provider.ts
packages/react-components/src/components/timegraph-output-component.tsx
yarn.lock

Make trace-extension compatible with latest timeline-chart

---

packages/base/src/signal-manager.ts
packages/react-components/src/components/abstract-output-component.tsx
packages/react-components/src/components/abstract-tree-output-component.tsx
packages/react-components/src/components/table-output-component.tsx
packages/react-components/src/components/trace-context-component.tsx
viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

Change widget colors based on theia themes

---

packages/base/src/experiment-manager.ts
packages/base/src/trace-manager.ts
packages/react-components/src/components/abstract-tree-output-component.tsx
packages/react-components/src/components/data-providers/style-provider.ts
packages/react-components/src/components/data-providers/tsp-data-provider.ts
packages/react-components/src/components/table-output-component.tsx
packages/react-components/src/components/timegraph-output-component.tsx
packages/react-components/src/components/trace-context-component.tsx
packages/react-components/src/components/xy-output-component.tsx
yarn.lock

Support fetching annotations and populating them in TimelineChart model

---

yarn.lock

Upgrade to latest timeline-chart version

---

yarn.lock

Uplift timeline-chart to fix resize issue #209

---

packages/react-components/src/components/abstract-output-component.tsx
packages/react-components/src/components/table-output-component.tsx
packages/react-components/src/components/trace-context-component.tsx
yarn.lock

Support synchronization of event table from time graph selection

---

viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

Don't omit file extension in trace name.

---

yarn.lock

Uplift timeline-chart to include fix for vertical scroll issue

---

packages/react-components/src/components/table-output-component.tsx

Pack event table columns on first model update

---

packages/react-components/src/style/output-components-style.css

Transforming the cursor into a cross-arrow when moving is possible
fixes #163

transforming cursor into cross-arrow when moving is possible #163

---

packages/react-components/src/components/timegraph-output-component.tsx

Update total height on toggle of node collapse/expand state

---

yarn.lock

Uplift timeline-chart to latest version

---

README.md
viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-analysis-widget.tsx
viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx

- Change "Trace Explorer" to "Trace Viewer"
- Change "Available Anlaysis" to "Available Analyses"
- The respective class names and files are not modified,
as it's a broader change.
Fixes #217
Signed-off-by: Ilya Mirsky <ilya.mirsky@ericsson.com>

Modify some UI labels

---

packages/react-components/src/components/timegraph-output-component.tsx

Reverts the exponential recursion back to a linear recursion. The linear
recursion should be addressed in a later patch.
Partially fixes
https://github.com/theia-ide/theia-trace-extension/issues/254

Fix exponential recursion when fetching timegraph tree

---

theia-extensions/viewer-prototype/package.json

Move tree-kill package from devdependencies to dependencies

---

packages/react-components/src/components/abstract-tree-output-component.tsx
packages/react-components/src/components/timegraph-output-component.tsx
packages/react-components/src/components/xy-output-component.tsx

The tree should not be re-fetched when the component is updated, as this
creates an endless loop of fetching the tree while the analysis is
running. Use a single fetch tree to both update the model and monitor
the analysis state. Introduce a delay between fetch tree iterations.
Update the chart while the analysis is running and once more on analysis
completion.
Always check that the tree model is defined before trying to access it.

Fetch the tree only while running analysis and use throttling

---

packages/react-components/src/components/table-output-component.tsx

Update Event Table row count during trace indexing

---

packages/react-components/src/components/xy-output-component.tsx

When clicking on the XY chart, the user can select a time.
When clicking and dragging, the user can select a time range.
fixes #121 

XY Chart: Support time and time range selection

---

packages/react-components/src/components/xy-output-component.tsx

Use plugin per chart instance instead of global for time selection

---

packages/react-components/src/components/table-output-component.tsx

Enable text selection in events table to allow copying

---

packages/react-components/src/components/table-output-component.tsx

Fix console warnings

---

packages/react-components/src/components/data-providers/tsp-data-provider.ts
packages/react-components/src/components/timegraph-output-component.tsx

Use trace range for time graph view boundary validation before a fetch

---

theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

Automatically switch to the trace explorer view after opening a trace.

---

theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

Fixes a regression.
Fixes #257

Set cancelable flag in progress monitor for opening of traces

---

packages/base/src/signal-manager.ts
theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-analysis-widget.tsx
theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-opened-traces-widget.tsx
theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

Set Focus to the trace viewer tab on click of analysis

---

theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-opened-traces-widget.tsx

Double click on experiment in trace explorer to open it

---

packages/react-components/src/components/xy-output-component.tsx
packages/react-components/style/output-components-style.css

Fix incorrect resizing of XY Charts

---

README.md
packages/react-components/src/components/trace-context-component.tsx
packages/react-components/style/trace-explorer.css
theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-opened-traces-widget.tsx
theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-views-widget.tsx
theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx

Fixes #292
Analyses are an abstract concept of computation, and more importantly,
the dataproviders are shown, they have a one for one relation to views,
but a many to one relation to analyses, so views is more accurate too.
Signed-off-by: Matthew Khouzam <matthew.khouzam@ericsson.com>

Analysis to view

---

theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

Fix toggling on click of open trace button

---

packages/react-components/src/components/timegraph-output-component.tsx
packages/react-components/src/components/xy-output-component.tsx
packages/react-components/style/output-components-style.css

Show spinning wheel when analysis is running for xy and timeline charts

---

packages/react-components/src/components/timegraph-output-component.tsx
packages/react-components/src/components/trace-context-component.tsx
packages/react-components/src/components/utils/time-axis-component.tsx
packages/react-components/src/components/utils/time-navigator-component.tsx
packages/react-components/src/components/utils/timegraph-container-component.tsx
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
yarn.lock

This PR needs timeline-chart https://github.com/theia-ide/timeline-chart/pull/121

Clean-up timegraph-container-component when closing widget

---

packages/react-components/src/components/data-providers/tsp-data-provider.ts
packages/react-components/src/components/timegraph-output-component.tsx
yarn.lock

Update for rename of TimeGraphRowElement to TimeGraphStateComponent

---

packages/react-components/src/components/utils/timegraph-container-component.tsx

Debounce resize handler for resizing timeline-charts

---

packages/react-components/src/components/table-output-component.tsx
packages/react-components/src/components/trace-context-component.tsx

Set selectionRange can take an undefined value, so onSelectionRangeChange should have an optional value for the range variable.
Useful for https://github.com/theia-ide/timeline-chart/pull/123

Check time selection range for undefined value

---

packages/react-components/style/output-components-style.css

Related to #240 
The title bar changes color when the cursor is on it.
I added a hover color in the css.
Here is the result.

Color change of the title bar on mouse over 

---

packages/react-components/style/trace-context-style.css

Reduce the resizable area of the widget

---

packages/react-components/package.json
packages/react-components/src/components/trace-context-component.tsx
yarn.lock

Make resize options identifiable

---

packages/react-components/style/trace-context-style.css

Change the placeholder background color

---

yarn.lock

Upgrade timeline-chart to version 0.2.0-next.e0da58ac

---

packages/react-components/src/components/table-output-component.tsx
packages/react-components/src/components/timegraph-output-component.tsx

Support Range selection synchronization between events table and timegraph chart

---

packages/react-components/src/components/data-providers/tsp-data-provider.ts
packages/react-components/src/components/timegraph-output-component.tsx
yarn.lock

This PR is dependent on: https://github.com/theia-ide/timeline-chart/pull/124

Add support for range events.

---

packages/react-components/src/components/timegraph-output-component.tsx
yarn.lock

Use opacity instead of alpha in timeline-chart style

---

packages/base/src/signals/signal-manager.ts
packages/react-components/src/components/timegraph-output-component.tsx
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-commands.ts
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.ts

depends on #https://github.com/theia-ide/timeline-chart/pull/140

Add Toolbar Icons for Zoom In, Zoom Out and Reset.

---

theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts

The current code in the `TraceViewerContribution` tracks the value of the preferences for port and path by listening to preference change events emitted by the `PreferenceService`. This can have unintended side effects because if a user resets a setting specified in a `settings.json` file, the [preference provider for that scope will emit an event](https://github.com/eclipse-theia/theia/blob/62116bfc756fcf61622f64646a831af78695beda/packages/preferences/src/browser/abstract-resource-preference-provider.ts#L230-L234) indicating that its local value has been set to `undefined`. The desired behavior of the `TraceViewerContribution` is that we should then use the default value, but the current code will use the `undefined` value.
This PR dispenses with the value tracking code in favor of …

Retrieve port, path values from PreferenceService as required

---

packages/react-components/src/components/trace-context-component.tsx

Add Time Axis only when time related chart is opened

---

packages/react-components/src/components/table-output-component.tsx

Allow events table search from the current selected row

---

packages/react-components/src/components/timegraph-output-component.tsx
packages/react-components/src/components/utils/time-axis-component.tsx
packages/react-components/src/components/utils/time-navigator-component.tsx
packages/react-components/src/components/utils/timegraph-container-component.tsx
yarn.lock

fixes #385
depends on https://github.com/theia-ide/timeline-chart/pull/143

Update Widget colors based on themes

---

.github/workflows/publish-next.yml

Fix token name for publishing to NPM

---

packages/react-components/src/components/timegraph-output-component.tsx
packages/react-components/src/components/trace-context-component.tsx

change the color of lineColor with #35373B for horizontal grid lines and #2B2E31 for vertical grid lines
**Here is the result in the screenshot :**
Fixes #441

Reduction contrast of grid lines

---

.vscode/launch.json

Fix source mapping for Chrome and Firefox launching

---

README.md

These updates were missed in recent PRs.

Update README to correct description of NPM package and electron app

---

theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
theia-extensions/viewer-prototype/src/common/backend-file-service.ts
theia-extensions/viewer-prototype/src/common/trace-server-config.ts
theia-extensions/viewer-prototype/src/node/backend-file-service-impl.ts
theia-extensions/viewer-prototype/src/node/index.ts
theia-extensions/viewer-prototype/src/node/trace-server-backend-module.ts

Move findTraces() to a backend service

---

theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

Fixes #569
Opening from the file explorer a trace uses the file URI to open the
the trace viewer widget. Then it scans the file system for traces,
posts the traces and experiment to the trace server. Only at that
point the experiment UUID is known. Theia keeps a map from
with a key using URI+TraceWidgetOpenOptions to widget. When opening the
first time the open options are undefined and the key is only the URI.
Closing the trace that map will cleared. When opening the trace from
the trace explorer, the TraceWidgetOpenOption will be populated with
the experiment UUID, but the URI is not known anymore.
When the user now opens the same trace from same file location, the URI
is used but the there is no way to know the corresponding UUID until
the trace(s) and experiment is created on the …

Fix duplicate tab when opening from file explorer that already is open

---

packages/base/package.json
packages/react-components/package.json
yarn.lock

Something with the `yarn.lock` prevented the application from building
in various environments.
Re-generate `yarn.lock`.

deps: fix build issue

---

README.md

Readme: Fix typo in react components NPM link

---

README.md

Readme: Add EclipseCon 2021 presentation

---

packages/base/src/experiment-manager.ts
packages/base/src/signals/signal-manager.ts
packages/base/src/trace-manager.ts
packages/react-components/src/trace-explorer/trace-explorer-opened-traces-widget.tsx
packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx
theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/theia-trace-explorer-opened-traces-widget.tsx
theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/theia-trace-explorer-views-widget.tsx
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

Pull Request #556 accidentally introduced a dependency to Theia in the react-components package which needs to be independent to Theia so that it can be re-used in other environments.

Remove Theia dependency in the react-components package

---

packages/react-components/src/components/xy-output-component.tsx

Remove unused Legend column of the tree in the xy-output-component

---

packages/react-components/src/components/xy-output-component.tsx

I can't find the issue that it was solving. It's something like "show data by default"

Add 'Nothing selected' when a chart is empty

---

packages/react-components/src/components/xy-output-component.tsx

Opening an Events Table and a XY chart like "CPU Usage" and clicking on
a row in the table was supposed to show a vertical line in the XY chart,
but this was not happening.
Selecting several rows in the table also was supposed to show a blue
selection area in the chart, which was not working either.
The selection would only work if, apart from opening an Events Table and
a XY chart, a status chart was opened, like the "Resources Chart".
Now all selections work.
Fixes #448.
Signed-off-by: Rodrigo Pinto <rodrigo.pinto@calian.com>
https://user-images.githubusercontent.com/88502808/147298134-175006d7-998f-4f9f-b436-9e4519301b4b.mov

Fix link between table event and XY chart

---

packages/react-components/src/components/xy-output-component.tsx
yarn.lock

Adapt to the change in the XYSeries model.

Change xValues to bigint array

---

packages/base/src/signals/signal-manager.ts
packages/react-components/src/trace-explorer/trace-explorer-opened-traces-widget.tsx
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts

Refresh Open Traces View after server start

---

.vscode/launch.json
doc/adr/0002-GraphQL.md
doc/adr/0002/graphql-server-prototype/README.md
doc/adr/0002/graphql-server-prototype/index.js
doc/adr/0002/graphql-server-prototype/package-lock.json
doc/adr/0002/graphql-server-prototype/package.json
doc/adr/0002/graphql-server-prototype/test

This PR is described in its commit message.

GraphQL ADR: prototype resolvers for tsp-client.ts

---

theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx

Re-add open trace button to Opened Traces view

---

packages/react-components/src/components/xy-output-component.tsx

Change the cursor when dragging with the left button (crosshair cursor)
and with the right button (ew-resize cursor).
The behavior of the xy-charts now is the same as on time-graph charts.
Fixes #636.

Change cursor on context clicks on XY-charts

---

.github/workflows/publish-next.yml

Update publish GitHub action to work with eclipse-cdt-cloud

---

yarn.lock

Signed-off-by: Patrick Tasse <patrick.tasse@gmail.com>

Upgrade to latest tsp-typescript-client version

---

doc/adr/0002-GraphQL.md

Base that content on a personal digest (an ADR-focused summary) of [1].
[1] https://app.pluralsight.com/library/courses/apollo-testing

GraphQL ADR: update content of Testability section

---

packages/react-components/style/trace-explorer.css
theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-widget.tsx
theia-extensions/viewer-prototype/src/browser/trace-server-status.ts
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-commands.ts
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx

Clarify when the Trace Server is Offline

---

doc/adr/0002-GraphQL.md

1. Finalize this initial draft version as the first proposal, to review soon.
2. Add high level use cases and stakeholders sections.
3. Replace theia-ide with eclipse-cdt-cloud across linked references.
4. Consistently use Markdown's numbering.

GraphQL ADR: prepare for initial team reviews; include high level use cases, stakeholders

---

packages/react-components/src/components/table-output-component.tsx

table: Fix time sync. when searching previous and next

---

packages/base/src/signals/signal-manager.ts
packages/react-components/src/components/trace-context-component.tsx
packages/react-components/src/components/utils/unit-controller-history-handler.ts
theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-keyboard-shortcuts/zoom-pan-shortcuts-table.tsx
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-commands.ts
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx

Adds the ability for the user to undo / redo changes made to the ViewRange and SelectionRange.  Adds buttons to the toolbar for these actions.

Undo / Redo Functionality

---

yarn.lock

Upgrade to timeline-chart 0.3.0-next.47c8e30.0 version

---

packages/react-components/src/components/data-providers/tsp-data-provider.ts

Use start time of time graph state to fetch tooltip

---

packages/react-components/src/components/timegraph-output-component.tsx

Signed-off-by: Patrick Tasse <patrick.tasse@gmail.com>

Enable coarse resolution update of time graph

---

packages/react-components/src/components/data-providers/tsp-data-provider.ts

Requests for States, Annotations, and Arrows are now fired simultaneously.
Annotation response data processing moved in front of states processing, since annotation response time is usually shorter.

Fire TSP client requests in parallel in getData function

---

theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

In markers menu add menu item to select/deselect all
fixes #770

Add select all and deselect all in marker menu

---

packages/react-components/src/components/timegraph-output-component.tsx

Clicking a marker on the marker axis would result in its time range to be selected in all views
fixes #768

Selection of time range through marker axis

---

packages/react-components/style/trace-explorer.css

Align with Theia colors.
Fixes #820

Update hover color in open trace explorer

---

theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

Making use of toDispose.push in the Trace Viewer Widget to dispose its event listeners so that they
don't cause memory leaks
Fixes #730

Fix Leaking TraceViewerWidget instances

---

packages/react-components/src/components/utils/filter-tree/table-cell.tsx

Fix onRowClick not a function error in table-cell

---

packages/react-components/src/components/timegraph-output-component.tsx
packages/react-components/src/components/xy-output-component.tsx
packages/react-components/style/trace-explorer.css

Fix padding in UI components

---

theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts

Fixes #827
[Screen Recording 2022-09-06 at 4.40.14 PM.webm](https://user-images.githubusercontent.com/92893187/188747202-4d1f02ed-b8b1-4402-bdf4-1702a83122cd.webm)

Fix issue with Start Trace Server command

---

doc/adr/0006-table-filtering.md

Add ADR about virtual table filtering TSP updates

---

README.md

This PR is to fix this rendering error:

Remove redundant ) in readme

---

packages/react-components/src/components/xy-output-component.tsx

Support window dragging with mouse-middle drag in xy charts

---

examples/electron/electron-builder.yml

Attempt to close https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/844
The following commands should work:
```sh
yarn
yarn --cwd examples/electron package
```

update target Electron version

---

.github/workflows/publish-next.yml

Upgrade node version to 16.x in publish workflow

---

theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

Add trace name to opening trace dialog box

---

yarn.lock

Uplift timeline-chart NPM

---

packages/react-components/src/trace-explorer/trace-explorer-opened-traces-widget.tsx

Add tooltip when hovering over trace in opened traces view

---

.gitpod.dockerfile

Use Java 17 in gitpod.dockerfile needed for latest trace server

---

yarn.lock

Upgrade to latest timeline-chart version "0.3.0-next.f029da1.0"

---

theia-extensions/viewer-prototype/src/browser/trace-explorer/trace-explorer-sub-widgets/trace-explorer-keyboard-shortcuts/charts-cheatsheet-component.tsx
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-frontend-module.ts
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-toolbar-contribution.tsx

Fix Issue with opening Shortcuts Dialog

---

doc/adr/0009-time-graph-search-functionality.md

Add ADR about time graph filtering TSP updates

---

packages/react-components/src/components/abstract-dialog-component.tsx

Update Select Overview Output Modal's state when its closed

---

package.json
yarn.lock

"react": "^18.2.0"
"react-dom": "^18.2.0"
"@types/react": "^18.0.15",
"@types/react-dom": "^18.0.6"

Upgrade React to match Theia's 1.34 react version

---

packages/base/src/signals/signal-manager.ts
packages/react-components/src/components/datatree-output-component.tsx
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx
theia-extensions/viewer-prototype/src/common/backend-file-service.ts
theia-extensions/viewer-prototype/src/node/backend-file-service-impl.ts

- Using Theia Backend to write files instead
- Users can choose file name/path in both browser & electron
- Show success/error message after

Export DataTree to csv through FileDialogService

---

theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer-contribution.ts

As previously flagged by SonarLint locally.

TraceViewerContribution: Fix this error assignment

---

packages/base/src/signals/signal-manager.ts
packages/react-components/src/components/datatree-output-component.tsx
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

Make csv export signal more generic so that it can be used by other outputs in the future

Rename csv export signal

---

README.md
examples/docker/Dockerfile
examples/docker/README.md
examples/docker/example-package.json
examples/docker/startup.sh

Resolves #908
Signed-off-by: Francesco Robino <francesco.robino@ericsson.com>

Add example of docker image for theia-trace-ext

---

.github/workflows/build.yml
.github/workflows/publish-next.yml

Use actions/setup-node@v3 instead of actions/setup-node@v1

---

lerna.json

This will permit publishing to npm using an automation token.
See: https://github.com/lerna/lerna/issues/2788#issuecomment-776726711

[lerna] option verifyAccess to false

---

packages/react-components/src/components/datatree-output-component.tsx

Fix missing horizontal scrollbar in data tree views

---

packages/react-components/src/components/__tests__/__snapshots__/table-renderer-components.test.tsx.snap
packages/react-components/src/components/abstract-output-component.tsx
packages/react-components/src/components/datatree-output-component.tsx
packages/react-components/src/components/timegraph-output-component.tsx
packages/react-components/src/components/xy-output-component.tsx
packages/react-components/src/components/xy-output-overview-component.tsx

This allows them to be used in vscode-trace-extension
Fixes https://github.com/eclipse-cdt-cloud/vscode-trace-extension/issues/108

Refactor Font Awesome icons in traceviewer-react-components

---

packages/react-components/src/components/abstract-output-component.tsx
packages/react-components/src/components/datatree-output-component.tsx
packages/react-components/src/components/drop-down-component.tsx
packages/react-components/src/components/table-output-component.tsx
packages/react-components/src/components/timegraph-output-component.tsx
packages/react-components/src/components/xy-output-component.tsx
packages/react-components/src/components/xy-output-overview-component.tsx
theia-extensions/viewer-prototype/src/browser/trace-viewer/trace-viewer.tsx

Changes made:
* Component-based drop-down menu implementation that takes showing condition, click function with argument
* Added support for exporting table data as csv for xy-output-component
This will provide export CSV option for XY graphs as well
Signed-off-by: Neel Gondalia ngondalia@blackberry.com

Added Export csv support for XY components

---

README.md

This PR is made of these two, rather simple commits:
1. `README: Fix these few left-over (yet minor) typos`
2. `README: Add a line about expecting ADR leadership`

README: Add line about expecting ADR leadership; fix a few typos

---

doc/performance/0001-timeline-chart-performance-analysis.md

This commit updates the performance analysis of the timeline chart since performance improvement are made. It records new statistics that is obtained from running the unit tests and Chrome profiler.

Update performance analysis on timeline chart

---

package.json
packages/base/package.json
packages/react-components/package.json
theia-extensions/viewer-prototype/package.json

Adds a package.json script to automatically fix linting errors in the 3 packages.

Add 'yarn lint:fix' Script

---

doc/adr/0011-tsp-analysis-api.md

Add ADR about external analysis API in TSP

---

doc/adr/0011-tsp-analysis-api.md

It advantage of having a more generic configuration API will allow for other types of configurations, for example Trace Compass server there could be marker definitions, custom parsers, filters etc managed through the same endpoint.

ADR: Generalize analysi-api ADR towards other configurations

---

.github/workflows/build.yml
.github/workflows/license-check-workflow.yml
.github/workflows/publish-next.yml
.gitpod.dockerfile
.vscode/settings.json
README.md
examples/browser/package.json
examples/docker/Dockerfile
examples/docker/example-package.json
examples/electron/package.json

Also update the required yarn version, that's somewhat related.
Fixes #1015

Update to node 18

---

.gitignore

Adding directory examples/plugins/ to .gitignore

---

.github/workflows/release.yml
lerna.json

Also got rid of the useless "lerna" line in `lerna.json`

[ci] prevent triggering release-related jobs on forks

---

packages/react-components/src/components/table-renderer-components.tsx
packages/react-components/style/output-components-style.css

Loading button is now displayed in the search bar. This fixes the issue where buttons shift whenever loading icon is displayed
Signed-off-by: Neel Gondalia <ngondalia@blackberry.com>

Fix buttons shifting when loading icon is visible

---

RELEASE
examples/browser/package.json
examples/electron/package.json
lerna.json
packages/base/package.json
packages/react-components/package.json
playwright-tests/package.json
theia-extensions/viewer-prototype/package.json

Release v0.2.3 (Patch)

---

RELEASE
examples/browser/package.json
examples/electron/package.json
lerna.json
packages/base/package.json
packages/react-components/package.json
playwright-tests/package.json
theia-extensions/viewer-prototype/package.json

Release v0.2.4 (Patch)

---

packages/base/package.json
packages/react-components/package.json
theia-extensions/viewer-prototype/src/browser/theia-rpc-tsp-proxy.ts
yarn.lock

timeline-chart: v0.3.2
tsp-typescript-client]: v0.4.2

Upgrade timeline-chart and tsp-typescript-client

---

RELEASE
examples/browser/package.json
examples/electron/package.json
lerna.json
packages/base/package.json
packages/react-components/package.json
playwright-tests/package.json
theia-extensions/viewer-prototype/package.json

Release v0.2.5 (Patch)

---

doc/adr/0011-tsp-analysis-api.md

Update 0011-tsp-analysis-api for custom analysis
- Introduce action endpoint and data structures for outputs
- Add example use case realizations using new API
- Use global configuration endpoint to manage data provider configs

Update ADR 0011-tsp-analysis-api for custom analysis

---

.github/workflows/ci-cd.yml

This makes sure that all necessary dependencies are available during publish.
Bernd Hufmann <bernd.hufmann@ericsson.com>

Add step to install dependencies on Ubuntu OS to publish workflows

---

packages/react-components/src/trace-explorer/trace-explorer-views-widget.tsx

It uses the parentId of the OutputDescriptor to group the data providers into a tree.
It depends on #1128 and PR to provide the parentId
 

Support tree hierarchy in Available Views view

---

RELEASE
examples/browser/package.json
examples/electron/package.json
lerna.json
packages/base/package.json
packages/react-components/package.json
playwright-tests/package.json
theia-extensions/viewer-prototype/package.json

Release v0.4.0 (Minor)

---

RELEASE
examples/browser/package.json
examples/electron/package.json
lerna.json
packages/base/package.json
packages/react-components/package.json
playwright-tests/package.json
theia-extensions/viewer-prototype/package.json

Release v0.4.1 (Patch)

---

RELEASE
examples/browser/package.json
examples/electron/package.json
lerna.json
packages/base/package.json
packages/react-components/package.json
playwright-tests/package.json
theia-extensions/viewer-prototype/package.json

Release v0.4.2 (Patch)

---

RELEASE
examples/browser/package.json
examples/electron/package.json
lerna.json
packages/base/package.json
packages/react-components/package.json
playwright-tests/package.json
theia-extensions/viewer-prototype/package.json

Release v0.4.3 (Patch)

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question.md
.github/PULL_REQUEST_TEMPLATE.md
SECURITY.md

This PR adds an issue and PR template in this repo, heavily inspired from those of the Eclipse Theia project (look at the raw files to see the parts that are comments):
[Theia Issue templace](https://github.com/eclipse-theia/theia/tree/master/.github/ISSUE_TEMPLATE) (composed of a few files)
[Theia PR template](https://raw.githubusercontent.com/eclipse-theia/theia/refs/heads/master/.github/PULL_REQUEST_TEMPLATE.md)
The new issue template will not be visible here until this PR is merged. To try it out immediately, head to my fork where I have temporarily updated master to contain this PR's commit:
https://github.com/marcdumais-work/theia-trace-extension/issues/new/choose
For the PR template, I'm using it right here (manually copied and filled-in). Much of the template is in the form of …

Add basic issue and pull-request templates

---

doc/adr/0012-data-provider-capabilities.md

Add ADR to add capabilities to output descriptors

---

examples/browser/package.json
examples/electron/electron-builder.yml
examples/electron/package.json
package.json
packages/react-components/package.json
theia-extensions/viewer-prototype/package.json
yarn.lock

Update extension, examples, to Theia 1.55.0.
Also yarn upgrade, some tidy-up, permit test example apps to use nodejs 18 and 20 (previously 16 and 18).
Had to add a couple resolutions:
- inversify: we were pulling a newer version than Theia 1.55.0 is using, that was causing issues
- @types/react: after yarn upgrade we were pulling / hoisting v18.3.18 which was causing build problems. Pinned to v18.3.8 which works well
Make sure CI passes. Optionally try new "base" and "react" packages in vscode-trace-viewer.
After this is merged, we will proceed with a release of the repo's packages to npm.

Update extension, examples, to Theia 1.55.0

---

RELEASE
examples/browser/package.json
examples/electron/package.json
lerna.json
packages/base/package.json
packages/react-components/package.json
playwright-tests/package.json
theia-extensions/viewer-prototype/package.json

Publish a new release of the npm packages in this repository.
Confirm CI passes.
N/A

Release v0.6.0 (Minor)

---

RELEASE
examples/browser/package.json
examples/electron/package.json
lerna.json
packages/base/package.json
packages/react-components/package.json
playwright-tests/package.json
theia-extensions/viewer-prototype/package.json

Patch release to include CSS fix.
Same behaviour as before.
N/A

Release v0.7.1 (Patch)

---

configs/license-check-exclusions.json
packages/base/package.json
packages/react-components/package.json
yarn.lock

Upgrade to tsp-typescript-client version v0.6.0
For release details see here:
https://github.com/eclipse-cdt-cloud/tsp-typescript-client/pull/128
Note: Ignore license check error because it's believed to be license-compatible, but still under review:
https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/19938
Successful CI run.
N/A

Upgrade to tsp-typescript-client version v0.6.0

---

RELEASE
examples/browser/package.json
examples/electron/package.json
lerna.json
packages/base/package.json
packages/react-components/package.json
playwright-tests/package.json
theia-extensions/viewer-prototype/package.json

Release v0.7.2 (Patch)
Successful CI run.
N/A

Release v0.7.2 (Patch)

---

yarn.lock

Bumps [axios](https://github.com/axios/axios) from 1.7.9 to 1.8.2.
- [Release notes](https://github.com/axios/axios/releases)
- [Changelog](https://github.com/axios/axios/blob/v1.x/CHANGELOG.md)
- [Commits](https://github.com/axios/axios/compare/v1.7.9...v1.8.2)
Successful CI run.
None

Bump axios from 1.7.9 to 1.8.2

---

RELEASE
examples/browser/package.json
examples/electron/package.json
lerna.json
packages/base/package.json
packages/react-components/package.json
playwright-tests/package.json
theia-extensions/viewer-prototype/package.json

New patch release of the npm packages in this repo.
CI passes.
N/A

Release v0.7.3 (Patch)

---

RELEASE
examples/browser/package.json
examples/electron/package.json
lerna.json
packages/base/package.json
packages/react-components/package.json
playwright-tests/package.json
theia-extensions/viewer-prototype/package.json

Release v0.8.0 (Minor)
N/A
N/A

Release v0.8.0 (Minor)

---

yarn.lock

Upgrade tar-fs to more recent versions.
Successful CI.
N/A

[security] Upgrade tar-fs to non-vulnerable version

---

RELEASE
examples/browser/package.json
examples/electron/package.json
lerna.json
packages/base/package.json
packages/react-components/package.json
playwright-tests/package.json
theia-extensions/viewer-prototype/package.json

Release v0.9.0 (Minor)
Confirm that CI passes

Release v0.9.0 (Minor)
